### ISSUE TITLE
 sh404SEF Integration - Use the K2 category's title instead of alias

### ISSUE THREAD

**Issue by ocanos** [getk2/k2#107]
Is possible that K2 Component in the future can add in: 
Advance / sh404SEF Integration / Use 'Title Alias' (instead of 'Title') for K2 URLs, but work with categories? 
Right now this tool configured with: No - use the item's title, converts the url so: 
domain.com/category/New-Article.html 
but no: 
domain.com/Category/New-Article.html 
You can add "No - use the category's title" in the future too? 
Thank you so much

**Comment by fevangelou** [comment]
We'll examine if it's possible in the upcoming K2 plugin for sh404SEF. Thanks for your input.

**Comment by fevangelou** [comment]
Released: http://www.joomlaworks.net/blog/item/263-new-extension-k2-plugin-for-sh404sef
