### ISSUE TITLE
Category image quality degraded when uploaded to server

### ISSUE THREAD

**Issue by veryans** [getk2/k2#136]
When a local file system image is selected for a category image and uploaded to the server it is saved on the server at a lower quality than the original despite the Quality (%) used when processing images in K2 component images being set to 100

**Comment by Maurafarah** [comment]
Hi all! I have the same problem, I upload the category image and it loses quality, quality its set to 100% and I upload exact to the same size (643px) configured in K2.

How can i tell K2 not to compress anything? If I download the image that has compressed K2 its 14kb the original its 90kb, so its blurry, could you please help me?

Thanks in advance!

Mauri
