### ISSUE TITLE
itemform.php override

### ISSUE THREAD

**Issue by schlagi123** [getk2/k2#163]
Hi,

I use Joomla 3.3 with K2.
I do not use any extentions for K2.

Problem:
I use a subtheme for a category in K2 (templates<template>\html\com_k2<subtheme>), but the itemform.php override is not working. K2 uses itemform.php everytime from the default subtheme.

I debug at line 135 in file \components\com_k2\controllers\item.php and see, that $params->get('theme') returns NULL everytime. In this case there is no chance to addTemplatePath of subthemes.

**Comment by williamconifer** [comment]
Is there any update on this? Kavadas marked this as an enhancement. We need to create custom versions of itemform.php that specifically appear based on the category of the item being edited or created.

**Comment by enricozamprogno** [comment]
We have the same problem. too.
There is something we can do inside default/itemform.php to test the k2 template or category ?
