### ISSUE TITLE
Multiple words in K2 Search system plugin

### ISSUE THREAD

**Issue by pvullioud** [getk2/k2#193]
the K2 search plugin not works if we type more than 1 word in the box.

Test case
I have an article with the text: "I like K2 as CCK"

Now I type in the search box: "I like K2". the system display the article. but, if I type in the search box: "like CCK" the system display: No results found!

PR will be done in a moment

**Comment by YaegerDesign** [comment]
I am still seeing this bug in K2 2.6.9. I cannot search for more than 1 word at a time. Otherwise, I get no results
