### ISSUE TITLE
conflict with bootstrap

### ISSUE THREAD

**Issue by oligalma** [getk2/k2#211]
Hi,
I'd like to inform you that there is a conflict between the k2 2.6.8 and the bootstrap 3.2.0: The images of the k2 items don't display. I've found that the problem is caused by the class="modal" of the links:

		  <span class="itemImage">
		  	<a class="modal" rel="{handler: 'image'}" href="/media/k2/items/cache/9caa2793658f3cc387f216157300b1ce_XL.jpg" title="Click to preview image">
		  		<img src="/media/k2/items/cache/9caa2793658f3cc387f216157300b1ce_L.jpg" alt="trousers 2" style="width:600px; height:auto;" />
		  	</a>
		  </span>

thanks for the attention,
Marc

**Comment by kavadas** [comment]
We need to wait for this. There is a related issue #246 .

**Comment by kricore** [comment]
My two cents here, since this modal is also used in the frontend editing panel, and this is the default modal of older Joomla! version (which are supported with this version), this needs to be solved in the template.

In the upcoming version where only Joomla! 3.x is supported the modal will be completely stripped.

**Comment by kricore** [comment]
MooTools will be completely dropped so this issue will be resolved.

**Comment by kavadas** [comment]
@kricore This has nothing to do with Mootools. It's the "modal" class name that conflicts with Bootstrap styles.

**Comment by kricore** [comment]
Since mootools will be removed and a new lightbox engine will be used, the
CSS class will also be changed, thus resolving this issue.

**Comment by kavadas** [comment]
@kricore 

No, that's not the case. The class name will probably maintained for backwards compatibility, for people that are using overrides.

**Comment by fevangelou** [comment]
Let's drop the CSS class. We'll add a notice in the release notes about it. Those who had the class on their overrides won't see a difference as the new initialization method is backwards compatible and will trigger the new modal. Obviously people who had the "modal" class so far either didn't use Bootstrap or they had used a workaround all this time.

So you @kavadas and @kricore you are both right :)

Closing this one.
