### ISSUE TITLE
Feature Request: add a new option of "show or hide comments moderating link" to K2 User module

### ISSUE THREAD

**Issue by baijianpeng** [getk2/k2#255]
hi, K2 User module will show the "Moderate comments to my published items" link by default, the worse is, there is no option to disable it. Many users had posted on K2 forum to ask "how to hide this link".

Well, Why not just add a new option in parameters of mod_k2_user like:

Show "moderate comments" link: Yes / No

Such an extra option will make admin easier to work.

Thanks.

**Comment by fevangelou** [comment]
Noted to add in 2.7.2.
