### ISSUE TITLE
[K2 2.7.0] Add "copy-" to URL Alias of Copied Items

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2#269]
Currently, copied items retain the same item URL alias - this can cause an issue if the admin forgets to change this, as the real item will not be accessible. 

I just realized this issue, when I forgot to delete the trashed copy of an item.

Automatically adding "copy-" before the item URL alias, similar to what's done for the item title would resolve possible issues.

**Comment by apooryousefi** [comment]
This would actually be the case when you copy in the same category. So in that case it's a good idea. 
But, when you copy some files from one category to another, there is no need to alter the alias or title.
