### ISSUE TITLE
[K2 2.7.0] Drop-down Extra Field Unique ID

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2#271]
Use unique ID's for drop-down extra fields, so when a value is deleted, the values beneath do not get effected.

**Comment by kavadas** [comment]
Hi Joe,

Can you clarify? How are the values affected currently?

**Comment by heyjoecampbell** [comment]
If you create drop-down extra field (Test Drop-down) with 3 values (A, B, C)

If you assign an item value "C" from the Test Drop-down > save

Then delete value A (from the extra field), you will see that the item extra field value that was "C" now is empty.

On the flip side, if you instead assigned the item value "B" from the Test Drop-down > save

Then delete value A (from the extra field), you will see that the item extra field value that was "B" now is "C".

Thus items are receiving the drop-down values based on positions (which can change) instead of a unique ID,

Please let me know if you require further clarification.

**Comment by heyjoecampbell** [comment]
Note: this request goes hand-in-hand with a previous request I submitted - https://github.com/joomlaworks/k2-v3-dev-build/issues/236
