### ISSUE TITLE
Feature request: more options for sh404SEF Integration

### ISSUE THREAD

**Issue by umiha** [getk2/k2#277]
I'm using K2 for content and sh404SEF for generating SEF links.

I understand that options for K2 plugin for **sh404SE**F is under K2 component's Configuration under "Advanced" tab, and under this group of options: "sh404SEF Integration"

Here is "sh404SEF URL category prefix for items", and I set this to "No categories" as I don't need categories in SEF url of the K2 item, but instead of categories I need some custom prefix for item link, some word like "article" or so. How can I achieve this? e.g. www.mydomain.com/custom-prefix/alias-of-article-title
It would be great if there exists option "Custom prefix for item URLs" ?

So, here I summarize the list of proposed options for "sh404SEF Integration":

1) add new option "Custom prefix for item URLs" without categories

2) change options for "Insert item ID in URL" from "Yes/No" to:
-No
-Yes, before Article Title e.g. www.mydomain.com/158-alias-of-article-title
-Yes, after Article Title e.g. www.mydomain.com/alias-of-article-title-158
To be able change the position of the ID inside item links, as this is possible for Joomla links inside sh404SEF Configuration, but not for K2.

3) the same options for "Unique ID"
-No
-Yes, before Article Title
-Yes, after Article Title

Thank you!

**Comment by fevangelou** [comment]
In K2 v2.7.0 we're separating all sh404SEF functionality to a Joomla plugin so we can adapt to changes and new features more rapidly.

I have already noted down your requests.

Thanks for your input.

**Comment by fevangelou** [comment]
Released: http://www.joomlaworks.net/blog/item/263-new-extension-k2-plugin-for-sh404sef
