### ISSUE TITLE
K2 Sub- and Child-Category Ordering Issue

### ISSUE THREAD

**Issue by paulcu** [getk2/k2#278]
On a live site, dev site and local install of Joomla v3.4.8 and K2 v2.6.9 we have found a possible issue with the ordering of K2 items. When we attempt to re-order items with the config shown below (multiple categories), the items will not stay in the order we choose but instead will reorder themselves randomly—that K2 does not properly save ordering at all. The ordering based on featured status can be set up once and will be retained as long as no further action is taken on the data. But as soon as any change is made to the data, whether it is to change the ordering of a single item, the creation of a new item, or the deletion of an existing item—essentially any CRUD action—the featured ordering is scrambled randomly. This appears to be the result of an AJAX error directly attributable to the core K2 code.

**Category Structure:**
Parent-Category
—Sub-Category
——Child-Category {items assigned}
——Child-Category {items assigned}
——Child-Category {items assigned}
—Sub-Category
——Child-Category {items assigned}
——Child-Category {items assigned}
——Child-Category {items assigned}

Local clean install without any additional extensions or plug-ins:
 
**Menu:**
Select Categories: {Parent-Category}
Fetch Items From Child Categories: {yes}
Item Ordering: {Ordering}
 
**Parent-Category:**
Category Item Layout / Other Layout Options / Featured Items: {Show Only Featured Items}
Category Item Layout / Other Layout Options / Item Ordering: {Ordering}
Category View Options / Sub-Category Handling / Sub-Category Ordering: {Ordering}
 
**Sub-Catgeory:**
Category Item Layout / Other Layout Options / Featured Items: {Show Only Featured Items}
Category Item Layout / Other Layout Options / Item Ordering: {Ordering}
Category View Options / Sub-Category Handling / Sub-Category Ordering: {Ordering}
 
**Child-Categories:**
Category Item Layout / Other Layout Options / Featured Items: {Show Only Featured Items}
Category Item Layout / Other Layout Options / Item Ordering: {Ordering}
Category View Options / Sub-Category Handling / Sub-Category Ordering: {Ordering}
 

In K2 Items we set Featured State to “Featured”, click on the double arrows to enable us to change the order of the Items, and move the items into a new order.
 
We then refresh the front-end but it does not match the the order we have set in K2 Items. If we refresh the back-end, the back-end then matches the front-end but the Items do not appear in the order that we had placed them—they instead change to some random order. We have tried this with different configurations of the Sub- and Child-Categories.

**Comment by kavadas** [comment]
Hi,

I cannot verify the issue. 

Here are some things you need to do:

1. Open a tool like phpmyadmin and look at the featured ordering column values before re-ordering any items.
2. Try to reorder featured items in the backend. Open the browser developer tools to see the request that K2 is making when you drop an item. Check the request's response status and text.
3. Access again phpmyadmin to see if the featured ordering of the item you dropped changed.
4. Open system debugger to see the queries executed in the lists ( both front-end and backend ) . Look out for the K2 items queries, they should end with something like "ORDER BY featured_ordering" .

**Comment by paulcu** [comment]
When we do this on our local clean install—that is move the order of one item in K2 Items as previously described—we still get this issue. When we refresh the views in K2 Items and on the front end, K2 does not honor our order but instead randomly changes the order of all the items. We get several errors:

**1) In the browser, console shows 2 jquery errors:**

Uncaught TypeError: Cannot read property 'length' of undefined        jquery.min.js:2
   m.extend.each @ jquery.min.js:2
   b.widget @ jquery.ui.core.min.js:5
   (anonymous function) @ jquery.ui.core.min.js:5
   (anonymous function) @ jquery.ui.core.min.js:5

Uncaught TypeError: Cannot read property 'length' of undefined       jquery.min.js:2
   m.extend.each @ jquery.min.js:2
   b.widget @ jquery.ui.core.min.js:5
   (anonymous function) @ jquery.ui.sortable.min.js:17
   (anonymous function) @ jquery.ui.sortable.min.js:17


**2) When we refresh phpmyadmin we get the following error:**

{
    "pma_version": "4.4.10",
    "browser_name": "CHROME",
    "browser_version": "48.0.2564.116",
    "user_os": "Mac",
    "server_software": "Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zd DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0",
    "user_agent_string": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "5.6.10",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read property '0' of null",
        "stack": [
            {
                "line": 235,
                "func": "",
                "context": [
                    "                lastException = null;",
                    "                notifyHandlers.apply(null, [stack, null].concat(args));",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "column": "",
                "filename": "tracekit/tracekit.js"
            },
            {
                "func": "getFieldValidators",
                "line": 302,
                "column": "40",
                "context": [
                    " * @return array of [function, parameters to be passed to function]",
                    " */",
                    "function getFieldValidators(field_id, onKeyUpOnly)",
                    "{",
                    "    // look for field bound validator",
                    "    var name = field_id.match(/[^-]+$/)[0];",
                    "    if (typeof validators._field[name] != 'undefined') {",
                    "        return [[validators._field[name], null]];",
                    "    }",
                    "",
                    "    // look for registered validators"
                ],
                "filename": "config.js"
            },
            {
                "func": "validate_field",
                "line": 418,
                "column": "21",
                "context": [
                    "{",
                    "    var args, result;",
                    "    var $field = $(field);",
                    "    var field_id = $field.attr('id');",
                    "    errors[field_id] = [];",
                    "    var functions = getFieldValidators(field_id, isKeyUp);",
                    "    for (var i = 0; i < functions.length; i++) {",
                    "        if (typeof functions[i][1] !== 'undefined' && functions[i][1] !== n//...",
                    "            args = functions[i][1].slice(0);",
                    "        } else {",
                    "            args = [];"
                ],
                "filename": "config.js"
            },
            {
                "func": "HTMLDocument.<anonymous>",
                "line": 511,
                "column": "13",
                "context": [
                    "    var $check_page_refresh = $('#check_page_refresh');",
                    "    if ($check_page_refresh.length === 0 || $check_page_refresh.val() == '1') {",
                    "        // run all field validators",
                    "        var errors = {};",
                    "        for (var i = 0; i < $elements.length; i++) {",
                    "            validate_field($elements[i], false, errors);",
                    "        }",
                    "        // run all fieldset validators",
                    "        $('fieldset').each(function () {",
                    "            validate_fieldset(this, false, errors);",
                    "        });"
                ],
                "filename": "config.js"
            },
            {
                "func": "HTMLDocument.new_func",
                "line": 279,
                "column": "33",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "HTMLDocument.m.event.dispatch",
                "line": 3,
                "column": "8436",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "HTMLDocument.$event.dispatch",
                "line": 374,
                "column": "19",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "filename": "jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "HTMLDocument.r.handle",
                "line": 3,
                "column": "5139",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "Object.m.event.trigger",
                "line": 3,
                "column": "7537",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "HTMLDocument.<anonymous>",
                "line": 3,
                "column": "15404",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            },
            {
                "func": "Function.m.extend.each",
                "line": 2,
                "column": "2973",
                "context": [
                    "/*! jQuery v1.11.1 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/li//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "if(k&&j[k]&&(e||j[k].data)||void 0!==d||\"string\"!=typeof b)return k||(k=i?a//...",
                    "},cur:function(){var a=Zb.propHooks[this.prop];return a&&a.get?a.get(this)://...",
                    ";",
                    "",
                    "function sprintf() {"
                ],
                "filename": "jquery/jquery-1.11.1.min.js"
            }
        ],
        "useragent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36",
        "incomplete": "false",
        "partial": "true",
        "uri": "sql.php?target="
    },
    "script_name": "sql.php",
    "microhistory": {
        "current_index": "0"
    }
}

**Comment by paulcu** [comment]
Any thoughts?

**Comment by paulcu** [comment]
Lefteris,

Have you been able to check on this? I tested this and sent you the results as well as posted in GitHub and haven’t heard anything back.

Paul

Design Associates Group, Inc. | 1828 Asbury Avenue | Evanston, Illinois 60201-3504 USA
W +00 1 847-425-4800 | C 312-215-2151 | Skype paul_uhl | DAG <http://www.designassociatesinc.com/> F <http://www.facebook.com/designassociatesgroup> IN <http://www.linkedin.com/in/pauluhl> T <http://twitter.com/daginc>

The information in or attached to this email may be confidential, may be legally privileged, and is not legally binding. It is intended only for the use of addressee. If you are not the intended recipient you must not disclose, copy, distribute, retain this message or any part of it, or take any action with reference to it. If you have received this e-mail in error, please notify the sender and delete the message from your system immediately. Any statement and/or opinion in this email not related to this company's business is solely that of the author and Design Associates Group, Inc. does not take responsibility for such statements or opinions.

**Comment by paulcu** [comment]
Today we updated K2 from 2.6.9 to 2.7.0 on our test site and retested the ordering issue and find that the problem still exists. 

On our local clean install (basic install of Joomla 3.4.8 and K2 2.7) without any additional extensions or plugins, we set the K2 items to ‘Featured” and changed their order. Without exiting K2 Items we viewed the front-end and find the items arranged in a different order than what we have set in K2 Items admin. If we refresh the K2 Items admin view, we then see that the K2 items in the admin are in a different order than what we've set—and which matches the order on the front end. K2 is still randomly ordering the items.

**Comment by paulcu** [comment]
We moved all our 'items' up a level, out of the child-categoiries into the two sub-categories that inherit from a parent category. With items set to 'featured' and parent and sub-categories set to display only 'featured' items by ordering, K2 still produces the same results—it randomly changes the order of the K2 items as described.

**Comment by paulcu** [comment]
• With the menu item for the parent category set to "Ordering" we get the above.
• With the menu item set to "Inherit From Category", we get the above.
• With the menu item set to "Featured First" it honors the default K2 Item view ("Select Featured State") with the ordering arrows unselected (just the two default up/down)

**Comment by paulcu** [comment]
I may have found the issue. 

In the MENU for the Parent Category, when I try to set the ITEM ORDERING under "Layout Options for Multiple Category Selection", it doesn't save any selection we make and ALWAYS saves back to DEFAULT.

**Comment by paulcu** [comment]
I've recorded the issues so that you can see what's happening. Other sites where we have K2 installed but not configured so that ALL items are "Featured" do not have this problem. We have tested this with all items in the parent category, with the items split between the two sub-categories as well as spread out among the child-categories all with the same results shown in this video: https://youtu.be/t30E1xzAJJA

**Comment by paulcu** [comment]
As a further test we have "un-featured" all our items, changed the parent category display items from "Show Only Featured Items" to "Show" and now all our items display properly. When we change the order in the K2 Items admin, the front end matches and the random scrambling of items does not occur.

The bug in K2 is with setting items to Featured and Show Only Featured Items and the video above shows.
