### ISSUE TITLE
404 error in latest build for gather.php

### ISSUE THREAD

**Issue by Twincarb** [getk2/k2#279]
I have installed the latest K2 dev 2.7.0 when in the administrator view there is a reference to gather.php
http://localhost/office/stats/gather.php is the link that it's looking for 
![k2_gather_php](https://cloud.githubusercontent.com/assets/14825222/13580173/01f360d6-e499-11e5-9c42-08719bcd4959.jpg)

**Comment by fevangelou** [comment]
This is still WIP. We're integrating anonymous metrics for K2 in general (you can opt-out of course) so in the long term we have a better view of who's using K2? The service will be public and it will collect stuff like K2 version, Joomla version, PHP version etc. but entirely anonymously. The script runs only in the backend asynchronously once a month only and pings the metrics server with the above data.

**Comment by fevangelou** [comment]
@Twincarb BTW, Paul Van Haren suggested I contact you regarding K2. What's the best way to do so? If you have a Twitter account, follow @joomlaworks and send me a DM if possible. Thanks.

**Comment by Twincarb** [comment]
I am following you on Twitter now @Dave_webber38. 
It certainly makes sense to have feedback on the systems everyone is using.

**Comment by fevangelou** [comment]
Thank you Dave. I've already sent you a DM over Twitter.

Closing this issue for now.
