### ISSUE TITLE
K2 using moo tools causing Menue-Problem in Joomla 3.5

### ISSUE THREAD

**Issue by franz-wohlkoenig** [getk2/k2#280]
Hi k2,

please have a Look: <a href="https://github.com/joomla/joomla-cms/issues/9329">Joomla! 3.5.0-beta5: Menu Item Type "K2 » Item listings » Categories" > Only Tabs "Details" and "Options" visible</a>

Regards

**Comment by fevangelou** [comment]
Thank you Franz. We'll investigate.

**Comment by kavadas** [comment]
Fixed with https://github.com/getk2/k2/commit/6d4cecd7229b4557c30e2020884d9dba07742298 .
