### ISSUE TITLE
Menu links to K2 category gets redirected to index page

### ISSUE THREAD

**Issue by KannanNaidu** [getk2/k2#281]
I just installed the latest build and not sure why but all my menu links to K2 categories gets redirected to index page. Links to other component like com_contacts is working. My URL rewriting is set to NO. 

I re-installed K2 with the version i downloaded in 20th Feb and the issue is gone and the menu links starts working. 

Did a test on a few site under development, and it's the same issue with the latest build. 

This happens to K2 categories with no items published in it. Once i publish an item, menu link will work.

**Comment by TGoodrich** [comment]
I downloaded and installed the latest K2 v2.7 on March 8, 2016 to my live site. After checking I can verify I am having the same issue. Before updating on March 8, K2 v2.7 was working great.

No pressure but I hope this can get figured out ASAP as this is a live municipal town website and I don't have an old v2.7 to revert back to. I know this is a dev build and I should have tested first but... Well no excuses, I had been having great luck with a previous build. I was in a hurry and pulled the trigger on the update.

**Comment by fevangelou** [comment]
This is probably a side effect of a new anti-spam feature we introduced recently. This feature redirects any user profile to the home page, provided the user profile contains no K2 items. Spammers did this to attach spam links on their own user profiles in Joomla/K2 sites.

We'll investigate further.

**Comment by KannanNaidu** [comment]
Thank you. Works like a charm.

**Comment by TGoodrich** [comment]
Thank you for the quick fix! Verified all is now working normally.

**Comment by kavadas** [comment]
@TGoodrich Thank you for your feedback.
