### ISSUE TITLE
Error installing K2 2.70 Dev build after todays commits

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2#282]
Warning

JInstaller: :Install: File does not exist /home1/***/public_html/tmp/install_56e1e18a92303/components/com_k2/js

Component Update: Failed to copy site files.

**Comment by kavadas** [comment]
We moved around some files and probably you got the package during this process. Can you please download a fresh copy from https://github.com/getk2/k2/archive/master.zip ? 

Let me know if you still get the error.

**Comment by Simon-Davies** [comment]
It is fixed and working now. Thanks mate. I'm the guy who emailed you last night btw haha :)
