### ISSUE TITLE
elFinder problem uploading file

### ISSUE THREAD

**Issue by gaelicwinter** [getk2/k2#283]
I have a case where I try to upload a jpg through the admin-side elFinder using the extra field of type image link.  The error returned is 'File type not allowed'.    I'm uploading a standard jpg file into an image extra field in the administrator, something we don't do very often.  My K2 version is from Dec 2015. Joomla ver is 3.4.8.

Through debugging in 

file: administrator/components/com_k2/lib/elfinder/elFinderVolumeDriver.class.php 
function: upload()

I see that $this->uploadAllow is set to allow a number of mime types, including 'image/jpeg', and $this->uploadDeny is an empty array.

When this code is executed:

`        
```
public function upload($fp, $dst, $name, $tmpname) {
...
        // logic based on http://httpd.apache.org/docs/2.2/mod/mod_authz_host.html#order
        $allow  = $this->mimeAccepted($mime, $this->uploadAllow, null);
        $deny   = $this->mimeAccepted($mime, $this->uploadDeny,  null);
...


public function mimeAccepted($mime, $mimes = array(), $empty = true) {
        $mimes = !empty($mimes) ? $mimes : $this->onlyMimes; // <-- This line
        if (empty($mimes)) {
            return $empty;
        }
        return $mime == 'directory'
            || in_array('all', $mimes)
            || in_array('All', $mimes)
            || in_array($mime, $mimes)
            || in_array(substr($mime, 0, strpos($mime, '/')), $mimes);
    }`
```

both $allow and $deny are set to true, and the upload fails.

There has been a recent update to elFinder in September 2015 which resolves this issue.  See issue here [https://github.com/Studio-42/elFinder/issues/1084](url)

The update looks like this:

```
public function mimeAccepted($mime, **$mimes = null**, $empty = true) {
        $mimes =** is_array($mimes)** ? $mimes : $this->onlyMimes; 
        if (empty($mimes)) {
            return $empty;
        }
        return $mime == 'directory'
            || in_array('all', $mimes)
            || in_array('All', $mimes)
            || in_array($mime, $mimes)
            || in_array(substr($mime, 0, strpos($mime, '/')), $mimes);
    }

```
I've patched my local install and confirm that it works.  

If you agree that this is indeed a problem, would it be possible to update elFinder in the K2 codebase?

Thanks,
Paul

**Comment by kavadas** [comment]
Hi,

I have tried to update elFinder for the upcoming 2.7.0 release but i faced some serious javascript conflicts under Joomla! 3.x . I will give it one more try. Thanks for reporting this.
