### ISSUE TITLE
Cannot Turn off Featured Star Icon

### ISSUE THREAD

**Issue by TGoodrich** [getk2/k2#285]
In Joomla 3.4.8 with latest build of K2 2.7.0 the featured Icon that appears next to item title cannot be turned off in settings.

The option is still there to turn the icon off but has no effect when setting it to not show icon. I have tried to set the icon to not show in my master category, the items category and the item settings but the icon still shows.

**Comment by TGoodrich** [comment]
Upon further investigation this may be a css problem. Enabling the featured flag adds the text "Featured" next to the item title and I have to assume this is the intended functionality to flag featured items.

The featured icon (shaped like a star) that can not be turned off, appears to be set by css if the item is set to featured. When the item is set to featured, "itemIsFeatured" class is added to the "k2Container" div.

"itemIsFeatured" class has a css :before selector that outputs the star icon. 

Not sure if the star icon is a work in progress or if the css accidently made it into the build.

**Comment by kricore** [comment]
Hello,

Can you send me a link to your site?
The "itemIsFeatured" class should only be printed if the item is indeed featured.

From the stylesheet I can see that the icon is only added when that flag is present
[code]
/* Font assignments */
div.catItemIsFeatured:before,
div.userItemIsFeatured:before,
div.itemIsFeatured:before{ content:"\e09b" }
[/code]

**Comment by kricore** [comment]
Update: I just tried it again with the default template and the icon can be turned on/ off from the feature from the backend switch. Let me know if you are still experiencing issues.

**Comment by TGoodrich** [comment]
Hi Kricore, thanks for looking into this.

I am still having the same issue. Please see the screenshot for details.

Also see this page - https://www.testing.townofsalisbury.org/conservation-commission/30/a-froggy-night-in-the-vernal-pool - This link takes you to a page where the featured flag is turned on in the backend and is also the page in the screenshot.

Also see this page - https://www.testing.townofsalisbury.org/conservation-commission/4/amphibian-nights - On this page the featured Flag has been turned off. The word "Featured" next to the title is gone but the "Star Icon" remains.

![featured-issue](https://cloud.githubusercontent.com/assets/10102765/13789074/d547d80c-eab8-11e5-9ce5-daf4ffd99341.gif)

**Comment by kricore** [comment]
Strange, 
Same code here, it works as intended.
The $this->item->featured flag is correctly printing (or not) the CSS class.

Have you tried turning it off and on again?
https://www.youtube.com/watch?v=nn2FB1P_Mn8

**Comment by TGoodrich** [comment]
Yes I have, also cleared template cache and browser cache - makes no difference.

Are we talking about the same switch?

My item is set to featured but  " 'Featured' notice (next to title) " switch does not turn off the star, only turns on and off the text "Featured".

Honestly looking at the code I'm not sure how the switch could turn the star off. 

Perhaps I'm missing something, When an item is set to "Featured" in the backend, "itemIsFeatured" class is added to the "k2Container" div. Once "itemIsFeatured" class is added then the css :before selector kicks in and the star icon appears.

I have featured items displaying on the frontend of my site but I do not want the featured icon star to be visible. I assumed that the backend switch " 'Featured' notice (next to title) " would turn that on or off.

**Comment by TGoodrich** [comment]
Maybe i'm not explaining the issue very well.

There are 2 options in the K2 Joomla backend for featured items.

The first option is to set the item as "Featured" and the second option is to turn the "Featured" notice on or off.

In the screenshot I sent the item is set by the first option as "Featured" so this item is a "Featured Item" and because it is set to featured the css class "itemIsFeatured" is added to the "k2Container" div.

For the second option, I have this turned off and assumed it would remove the Featured Icon but it doesn't. It on the removes the text "Featured" next to the item title.
![item-1](https://cloud.githubusercontent.com/assets/10102765/13791287/b7fd394a-eac2-11e5-8680-f28bfcd8a896.gif)
![item-2](https://cloud.githubusercontent.com/assets/10102765/13791290/bc27d70a-eac2-11e5-8b68-4e8416ecd423.gif)

**Comment by paulcu** [comment]
I have the same issue. I've turned off the 'Featured' icon for the Category and all of the items and it still appears.

**Comment by TGoodrich** [comment]
Forgot to comment on this, several times I've tried turning it off and then on again. No change but thanks for the video.. Loved it lol - to funny!!

**Comment by kricore** [comment]
You 're welcome. Actually the switch i side the item's form controls the
featured flag entirely. The second option only controls only the featured
text.
The second switch only hides/ shows that text. It will not control the
item's status nor it will apply any CSS classes.
On 15 Mar 2016 23:07, "TGoodrich" <notifications@github.com> wrote:
>
> Forgot to comment on this, several times I've tried turning it off and
then on again. No change but thanks for the video.. Loved it lol - to
funny!!

**Comment by TGoodrich** [comment]
Ok so if I understand correctly it is working as designed. Maybe we could make it an enhancement  request to have a separate switch for the for the icon star or get rid of it all together. It seems like it would be enough to have only one reference to an item being featured. By that I mean there is already the switch that adds a featured flag by way of adding the text "Featured" next to the item title. Why also have the star icon?

Currently myself the "user" could just make a css override to remove the star but that just makes me have to write more code.I know it's not much but..

You may be thinking, well just turn off the first featured switch and problem solved. Let me give you an example why that wouldn't work for me. I use RokSprocket from Rockettheme and have it set to show only featured items on the homepage of my website. Because of this I need to set certain items as "Featured" in the item's parameters. The great thing about this is that featured acts like a filter and I can change an items featured state on the fly just as easy as I can publish and unpublish an item while viewing my list of items in the backend.

Having 2 featured flags is confusing to me especially with the fact that one can be turned off but not the other. Myself and maybe also others might set items to featured so that items can be filtered by "Featured Items Only" and have no need to announce that those items are featured.

Hope all this makes sense?

**Comment by kricore** [comment]
Actually this behaviour has been around for ages.
We just updated the ribbon which was looking (a lot) out of date with a retina-ready icon font.

Instead of removing the rules about the image you simply remove the 3 lines I sent you above.
Adding a 3rd switch is an overkill imho and it will clutter the UI.

I will leave this issue open however since other users might want to propose something.

**Comment by moXion** [comment]
Hi all,
For me, the most simple solution is add css with:

.catItemIsFeatured::before {
display: none;
}

I hope this help.

**Comment by chrisvphogan** [comment]
As stated above by 'moXion' the css code he mentions works in a custom.css file in your templates css folder!
