### ISSUE TITLE
sh404sef URL bug

### ISSUE THREAD

**Issue by ajmaxpaul** [getk2/k2#287]
Hello

I was using K2 Version: 2.6.9 on a test sever with sh404sef and the SEF url was working as desired. 
**e.g: www.domain.com/category/page_title**

When i upgraded to K2 2.7, i noticed that all new url was being created in the following format:
www.domain.com/item/itemID_page_title
**e.g: www.domain.com/item/250_page_title**

The word "/item/" appears in the url.

I tried to disable options like disable category id and page id from url etc but nothing seems to be working.

Looks like a component specific bug in K2 V2.7

Can you please look into this issue?

Thanks

**Comment by fevangelou** [comment]
Please read this: http://www.joomlaworks.net/blog/item/263-new-extension-k2-plugin-for-sh404sef
