### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Edward0625** [getk2/k2#290]
Hi!

In back-end, category list have an errors:

jquery.min.js:2 Uncaught TypeError: Cannot read property 'length' of undefined

Thank you!

**Comment by fevangelou** [comment]
What Joomla version?

If it's not Joomla 3.x, what jQuery are you loading in the backend via K2?

Is there any other plugin executing on the category listing view in the backend (usually system plugins may do this if they are not properly contained)?

**Comment by Edward0625** [comment]
Hello!

Joomla version is 3.5 and k2 is 2.7.1 dev.

I copy the errors from Mozzila console:
TypeError: a is undefined    jquery.min.js:2:2817
.each() jquery.min.js:2
b.widget() jquery.ui.core.min.js:5
<anonymous> jquery.ui.core.min.js:5
<anonymous> jquery.ui.core.min.js:5

TypeError: a is undefined    jquery.min.js:2:2817
.each() jquery.min.js:2
b.widget() jquery.ui.core.min.js:5
<anonymous> jquery.ui.sortable.min.js:17
<anonymous> jquery.ui.sortable.min.js:17 

This errors appear just in category list.

Thank you.
