### ISSUE TITLE
2.7.0 Image upload issue

### ISSUE THREAD

**Issue by sevenstudio** [getk2/k2#292]
I had an issue with uploading image for K2 article after upgrading to 2.7.0. (J 3.5.0).

Selected image was ignored on save (no problem with file size, extenstion, upload size and other PHP settings). 

There was NO problem with image that was selected from the server. (proccessed as it should).

Upgrading PHP version from 5.3.29 to  5.5.33 solves this problem.
Don't have time to debug this further, but if requirments for 2.7.0 has been changed this should be clearly stated.

**Comment by kavadas** [comment]
The requirements have not been changed. Probably the server was not able to detect the correct mime type for the upload.

**Comment by kavadas** [comment]
This should have been fixed already with http://www.joomlaworks.net/forum/k2-en/45116-image-upload-error-k2-7-and-j3-5 .

**Comment by sevenstudio** [comment]
Thank for the update, @kavadas
I can confirm that the latest dev version with that change solves problem in older version of PHP.
