### ISSUE TITLE
Filter categories by language issue

### ISSUE THREAD

**Issue by acs-ferreira** [getk2/k2#298]
## It works if
1. Filter by category
2. Then, filter by language

http://s20.postimg.org/iwjtfj0kd/screenshot_135.png
## It does NOT work if
1. Filter by language **only** without previously chose a category

http://s20.postimg.org/vp7xfgc65/screenshot_136.png
### Output:

```
Notice: Undefined offset: 0 in /administrator/components/com_k2/models/categories.php on line 106

Notice: Trying to get property of non-object in /administrator/components/com_k2/models/categories.php on line 106
```

**Comment by kavadas** [comment]
I cannot verify the issue. Are you using the 2.7.1 dev build? 

This seems the same as #289

**Comment by acs-ferreira** [comment]
No, v2.7.0, but i'll try https://github.com/getk2/k2/commit/2cb13bd61abdfcae51158cc645495428b02c5fd3

It seem the same issue than #289
