### ISSUE TITLE
Newly created Attachment does not store the value in the correct element.

### ISSUE THREAD

**Issue by kricore** [getk2/k2#302]
The value is being stored in the <button> and not in the input field.

**Comment by fevangelou** [comment]
In the what?

**Comment by kricore** [comment]
The <button> sorry.

http://imgur.com/PK4CouY

**Comment by mschultze** [comment]
The value is being stored in the button element and not in the input field.
The error is in the k2.js in media/k2/assets/js on line 490:
"var k2ActiveAttachmentField = $K2(this).next()"
the next element is not the input field, it is the cancel botton on the right side
i use this
"var k2ActiveAttachmentField = $K2(this).next().next()"
this works

**Comment by teobgeno** [comment]
Thank you @mschultze for the fix just commit it to the repo.
