### ISSUE TITLE
Information Discolsure

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2#303]
Can you please delete this comment from the source code:

JoomlaWorks "K2" (v2.7.1) | Learn more about K2 at http://getk2.org

It tells hackers that the website is running Joomla if they View Page Source.

I know there are other indicators i.e. the robots.txt but this can be deleted and replaced with the X-Robots-Tag HTTP header in a .htaccess file in each folder.

The administrator login can also be hidden with a secret prefix i.e. domain.com/administrator?secret

**Comment by dgt41** [comment]
@Simon-Davies There are a gazillion ways to see if a site is based on Joomla...

**Comment by Simon-Davies** [comment]
Most can be mitigated i.e. Hiding the obvious give aways using Admin Tools, using SEF URLs

**Comment by dgt41** [comment]
how about downloading an xml file: e.g. `http://localhost/administrator/components/com_categories/categories.xml`
This is not a real problem IMO

**Comment by Simon-Davies** [comment]
Doesn't work ;)

403 Permission Denied

You do not have permission for this request /administrator/components/com_categories/categories.xml

**Comment by dgt41** [comment]
Try: ```https://www.joomla.org/administrator/components/com_categories/categories.xml```

**Comment by kricore** [comment]
Even if one file is not available, the folder structure is a giveaway.

Try requesting an .ini file.

Built with and wappalyzer will still recognize Joomla! no matter what.

There are a million ways to detect Joomla! an HTML comment will not hurt
your site in any way.

**Comment by Simon-Davies** [comment]
This has been an interesting discussing. Thank you kricore as I didn't know about that extension but it's extremely handy. Do you know how it detects Joomlas presence. It would be really interesting to know

**Comment by acs-ferreira** [comment]
Yuu can minify the HTML and strip the comments.
Example: https://www.jch-optimize.net/documentation/plugin-options.html

**Comment by fevangelou** [comment]
This identifier is there for 2 reasons. a) For support to quickly check which version of K2 is running on your system and b) for Wappalyzer which gathers usage statistics for various apps and CMSs. It's not gonna change and it surely doesn't give away any more than Joomla already gives with a simple "curl -I domain.tld" from a terminal. K2 has NEVER had any security issues. Let this boil in for a second.

**Comment by Simon-Davies** [comment]
It's still classed as Information Disclosure if a website was to ask for a penetration test. I was only asking though you don't have to get annoyed I support K2 development :)
