### ISSUE TITLE
Change Author Link Missing V2.7.0

### ISSUE THREAD

**Issue by lollypop27** [getk2/k2#305]
Love the new layout
Change Author Link Missing under publishing & metadata tab, see attched
![author-change-link](https://cloud.githubusercontent.com/assets/5736248/14402809/0e5fcbaa-fe40-11e5-929c-5158fa8a2eb4.jpg)

**Comment by fevangelou** [comment]
Not really. The link to change the author was simply moved where it should be, right below the title, category etc. in the new "Basic" tab. See screenshot: http://jmp.sh/LvhX2E0
