### ISSUE TITLE
Some extra field missing in add new item - ver 2.7

### ISSUE THREAD

**Issue by etagure** [getk2/k2#306]
Hi I upgraded K2 to new 2.7.1 dev. When add new item in backend, I choose category for item and only one extra field is shown. I have 5 extra fields. When hit save all extra fields are shown.
1. Extra field tab before choose category (this is OK) www.dropbox.com/s/ssm9gxcowarmoyz/Screenshot%202016-04-05%2000.28.47.png?dl=0
2. Extra fields tab when choose category (4 extra fields missing)
www.dropbox.com/s/w7i2hpb5gh4m7z5/Screenshot%202016-04-05%2000.29.07.png?dl=0
3. Extra field when click save item (all extra fields shown)
www.dropbox.com/s/b5z64p9dyh1y1g6/Screenshot%202016-04-05%2000.29.26.png?dl=0

So, problem is that only one extra field is shown. When click save than all extra fields are shown. In K2 2.6.9 all was OK
Thnx for help

**Comment by KannanNaidu** [comment]
I can confirm this. It works fine on K2 2.7.0.

Happens only on the dev version of K2 2.7.1

Tested on Joomla 3.5.1 with PHP 7.0.0

**Comment by KannanNaidu** [comment]
Thank you. Works like a charm now.

**Comment by etagure** [comment]
Yes it works, thank you
