### ISSUE TITLE
Disable K2's User Profile

### ISSUE THREAD

**Issue by acs-ferreira** [getk2/k2#307]
It seems that the option to disable the K2's User Profile is not working.
![datacenterdynamics](http://s20.postimg.org/u13b7unj1/screenshot_139.png)

On the frontend:
![datacenterdynamics](http://s20.postimg.org/w87jvrst9/screenshot_140.png)

K2 v2.7.0

**Comment by teobgeno** [comment]
Tested with the same settings as yours and is function properly. Are you using the default Joomla registration output from users component ?

**Comment by acs-ferreira** [comment]
Yes, default output used, no overrides.
