### ISSUE TITLE
Issue using Falang 2.5

### ISSUE THREAD

**Issue by kricore** [getk2/k2#314]
Deleting items produces

1054 Unknown column 'Array' in 'where clause' SQL=SELECT c.id, c.title, c.alias, c.introtext, c.fulltext, c.image_caption, c.image_credits, c.video_caption, c.video_credits, c.extra_fields, c.extra_fields_search, c.metakey, c.metadesc, jfc.id as jfc_id, jfc.value as titleTranslation, jfc.modified as lastchanged, jfc.published as published, jfc.language_id, jfl.title as language, jfc.reference_id as jfc_refid FROM #__k2_items as c LEFT JOIN #__falang_content as jfc ON c.id=jfc.reference_id AND jfc.reference_field='title' AND jfc.reference_table='k2_items' AND jfc.language_id=3 LEFT JOIN #__languages as jfl ON jfc.language_id=jfl.lang_id WHERE c.id=Array ORDER BY c.title

**Comment by scalpmonkey** [comment]
Also for pressing any button in Items page in my case.

**Comment by teobgeno** [comment]
I cannot reproduce the issue. can you provide me with more details ?

**Comment by mahalo39** [comment]
I'm facing exactly the same issue after updated Joomla and K2. (Joomla 3.5.1 + K2 v2.7..0 + FaLang 2.5.0)
This error occurs on administrator screen of items list, categories list, tags list (for example), whenever you tried to trash/publish/unpublish any of the item/category/tag. 
(If you open an individual item and click unpublish/publish button, it works without error.)

Attached are the list of FaLang plugins I'm using just in case you need. 
![falang_plugins](https://cloud.githubusercontent.com/assets/19278729/15135690/423e9ab4-16b4-11e6-9f8c-484d66683771.png)

**Comment by sbouey** [comment]
Hi,

It's fixed in the next release of Falang > 2.5.0  , the 2.7.0 of k2 change the return of $id to array.
line 226 of plugins/system/falangquickjump/falangquickjump.php
you can add this
if (is_array($id)){$id = $id[0];}

just before the 
        //Load ToolBar
        $bar = JToolBar::getInstance('toolbar');

Stéphane
Falang Team

**Comment by kricore** [comment]
Closing this issue since it will be included in Falang's latest release.
