### ISSUE TITLE
all content items and categories not showing in back end

### ISSUE THREAD

**Issue by corconsulting** [getk2/k2#317]
i reviewed other posts for different versions of k2 but i am reluctant to make changes to code since i presume those changes were already adopted in the past. I logged in today and no categories or items are displayed and changing the filter on language to all even though there is only one language (en-gb) nothing happened and the filter did not reflect that i had changed it to all.

i tried fixing the db and clearing cache and eventually even reinstalling k2 but like others this had no effect. I tried creating a new item and using sort filtes to find specific items and i can't get them to show. everything is working on the front end though.

Joomla! Version	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
K2 v2.7.0 (i was already on this version but reinstalled it)
Using Chrome. Cleared my Chrome cache. Version 50.0.2661.94 m
Tested in Firefox and i didn't have a problem.

i never had problems with chrome in the past.

Any suggestions on how to proceed.

**Comment by corconsulting** [comment]
now it's not working in firefox either.

**Comment by corconsulting** [comment]
my client in a different location is reporting the same issue now

**Comment by kavadas** [comment]
Check your database to ensure that items are still there. You should look at the #__k2_items table.

Note that if you have uninstalled K2 you have lost your data and there is nothing you can do if you don't have a backup.

**Comment by corconsulting** [comment]
all content is intact and nothing wrong with database. the front end of the site is perfect and as i stated above i AM able to see it for a limited time if i use a new browser. i can see all content from my mobile device in the back end. this issue is posted at the k2 forum and other people are posting about this since the 2.7 update. Attached are screenshots taking with both browsers open. in Chrome and Firefox the content is missing and as you can see there are no errors in the console. in slimjet i was able to view everything normally. firefox worked for about 30 minutes before it had the same problem. See the full spectrum of my posts and what i have tried and checked here: http://www.joomlaworks.net/forum/k2-en/45542-items-and-categories-not-showing-in-back-end-2-7

![holisticbackendk2issue_slimjet](https://cloud.githubusercontent.com/assets/5391262/15032916/be35ab6a-1233-11e6-9923-553178314a8f.png)
![holisticbackendk2issue2](https://cloud.githubusercontent.com/assets/5391262/15032917/be3775ee-1233-11e6-9cd3-29edab91a623.png)

**Comment by teobgeno** [comment]
Can you send a Joomla debug output from this K2 item list ?

**Comment by corconsulting** [comment]
turned out to be a cookie issue. resolved once cookies cleared

**Comment by corconsulting** [comment]
actually this is not resolved and the matter continues. however it appears that it is a conflict with a cookie from mijoshop and other people who have this problem also have mijoshop installed but it only started after the 2.7 update. every time you browse to a page that contains mijoshop content the k2 admin interface gets messed up with respect to items and categories going away. it's not really a solution to have to clear cookies and cache every time and my client is getting frustrated with this "solution". there are tickets filed with mijoshop and more details on the thread in the forum for k2

MIJOSHOP-0V92ZGM26Q 
http://www.joomlaworks.net/forum/k2-en/45542-items-and-categories-not-showing-in-back-end-2-7

**Comment by kricore** [comment]
Hello to all,

Mijoshop appears to have releasead an update which solves the issue.
More info here: http://www.joomlaworks.net/forum/k2-en/45542-items-and-categories-not-showing-in-back-end-2-7?start=30#154772
