### ISSUE TITLE
PHP Notice:  Use of undefined constant DS - assumed 'DS'

### ISSUE THREAD

**Issue by davenir** [getk2/k2#318]
/administrator/components/com_k2/models/item.php on line 15

**Comment by kavadas** [comment]
Hi,

The constant is defined in the K2 system plugin so it should be available. Unless you are using the item model outside K2 context.

**Comment by davenir** [comment]
This was part of a K2 upgrade. The K2 system plugin was installed but it made no difference. In the end we had to uninstall and revert back to earlier K2 version. V3 looked great though - looking forward to it!

**Comment by kavadas** [comment]
Which page are you viewing when you get the notice?

**Comment by davenir** [comment]
Home page

**Comment by kavadas** [comment]
I need more information. Is this coming from a module? Or the component? If it's the component, what kind of menu type is used on your home page?

**Comment by davenir** [comment]
I'm sorry Kavadas - I can no longer replicate the error. As I mentioned in my earlier post:

"In the end we had to uninstall and revert back to earlier K2 version."

Our Joomla version was an upgrade from 2.5 so it's proably safe to close this issue. 
Thanks for your response.
