### ISSUE TITLE
K2 article file attachment location is predictable

### ISSUE THREAD

**Issue by shoulders** [getk2/k2#326]
Hi

This issue is present in  k2 v2.6.9 and v2.7.0

when you add an attachment to a K2 article this file is uploaded to **/media/k2/attachments/**

If you know the file name you can bypass the K2 download mechanism which is a bit of a security issue or at least a control issue.

My solution would be to add a random 5 character suffix on the end of every file before being added to the files repository which would prevent guessing the direct URL. When the file is download the file is renamed on the fly before the file is presented to the user for download. I would also use the normal filename for display in the admin section and the article for download so there is not confusing. The suffix should be for internal K2 use only.

This solution would also solve filenames that are the same.

**Comment by Simon-Davies** [comment]
This is a very good idea. Being able to guess and force browse to restricted material is Broken Session Management and a security flaw

**Comment by kavadas** [comment]
If you want to restrict downloads you can simply change the attachments root folder in K2 parameters.

**Comment by shoulders** [comment]
quick followup, if i download 1 file/attachment from the said website this would then allow me to predict every other download

**Comment by Simon-Davies** [comment]
This is not invalid kavadas. I work as a Penetration Tester and shoulders is right, it's a very valid issue security wise.

**Comment by fevangelou** [comment]
That is why we allow changing the path to the attachments folder, which can be entirely outside your working web folder. In that case, directly downloading a file is simply impossible. The solution is there since day 1. Let's not overcomplicate things.

**Comment by shoulders** [comment]
Not everyone has access to put stuff outside their working web folder, and I think doing that, does over complicate things. Most end users will not be able to do that.

**Comment by fevangelou** [comment]
Every web hosting account offers a public_html folder and access to other folders below that public_html folder which are not publicly accessible. And even if you happen to host a site where such an option is not possible (although highly unlikely) you can use any other folder inside your site. However, if your files are named file1.zip, file2.zip and so on, that's not really K2's problem. BTW, renaming the files will break a ton of other integrations. If you have specific needs, have a look at dedicated file/document managers. K2 is multi-purpose, built with simplicity in mind and should remain that way.

**Comment by shoulders** [comment]
"However, if your files are named file1.zip, file2.zip and so on, that's not really K2's problem."

they dont need to be named in sequence. i could write a simple script to scrape the files names from the articles and then add in the base folder location and then I can harvest all files (assuming not in the web directory).

"BTW, renaming the files will break a ton of other integrations. If you have specific needs, have a look at dedicated file/document managers." unless the files are referenced directly by various different scripts you could add some code in between the request and the file to perform on the file rename etc.. 

I do not need a dedicated file manager because the reason i want this feature is to add the assets for the particular coding project of that page. Attachments are better and more relevant than a separate download, but as is opens me up for file scraping.

thanks anyway

**Comment by fevangelou** [comment]
Again, I don't see the problem. You have options. It's your choice NOT to use a private folder. When we operated nuevvo.com with Joomla templates, we served all paid downloads from a private location. Worked like a charm. What you ask is a solution to fit your needs specifically, not necessarily everyone's needs.

**Comment by shoulders** [comment]
For reference:

> That is why we allow changing the path to the attachments folder, which can be entirely outside your working web folder. 

not possible on one.com
