### ISSUE TITLE
K2 article attachment weired file renaming

### ISSUE THREAD

**Issue by shoulders** [getk2/k2#327]
When I uploaded the file **Promo-Intro-Text Improved.zip** as an attachment it changed the name to **Promo-Intro-TextZImproved.zip** . Notice that the space was changed to a capital Z.

I would expect the normal behavior to change it to a dash - not a Z

**Comment by fevangelou** [comment]
Just tested, it works as expected. Perhaps a hidden character caused this.

**Comment by shoulders** [comment]
it is the space. there were no hidden characters (not that i even know how to do that)

tar
