### ISSUE TITLE
Missing information in modal

### ISSUE THREAD

**Issue by ronnyvanderborght** [getk2/k2#330]
The k2 modal (when adding a k2 menu-item) is missing important information. There is no language-column and no way the filter the items bij category, language etc...
On multilingual sites or sites with a large number of k2 items it is really difficult to find the correct k2 item needed for the menu-item.

**Comment by ronnyvanderborght** [comment]
Some more info on this.

The problem is there because the modal is only 700px wide, because the content is an iframe it triggers the 'hidden-phone' style, and thus hiding al available filter.
As a workaround you can add this style to the ISIS admin template:

#sbox-window {
    height: 450px  !important;
    width: 80% !important;
	left: 10% !important;
}
#sbox-window iframe {
    height: 450px  !important;
    width: 100% !important;
	left: 0 !important;
}

**Comment by ronnyvanderborght** [comment]
Some more info:

To add more columns (in this case the column 'language') to the table shown in the modal: modify /administrator/components/com_k2/views/items/tmpl/

To add the 'language column', after line 48 add:

<th><?php echo JHTML::_('grid.sort', 'K2_LANGUAGE', 'i.language', @$this->lists['order_Dir'], @$this->lists['order'], 'element'); ?></th>

end after line 61 add:
<td class="k2Date"><?php echo $row->language; ?></td>

**Comment by kricore** [comment]
Closed with https://github.com/getk2/k2/commit/80c9857bda83b833ae9d5abb8c960af3b676d1da
