### ISSUE TITLE
Extra fields validation, styling issue.

### ISSUE THREAD

**Issue by sevenstudio** [getk2/k2#331]
K2 2.7.0. 

Validation of extra fields has a bug in styling, if you leave empty field that is required, during saving you will get:

http://imgur.com/C5PzNNG

proposed simple fix:

from media/k2/assets/css/k2.css
please remove lines:

<code>72. #k2ExtraFieldsValidationResults,</code>
...
<code>77. #k2ExtraFieldsValidationResults {background-position:-10px -92px;width:59px;height:54px;}</code>

and you will get:

http://imgur.com/V9cLB7i

Please take a look at this issue.

**Comment by kricore** [comment]
Hello,

This has already been corrected in the repo.

**Comment by sevenstudio** [comment]
Hello kricore, thank you for your reply!
Any plans to release 2.7.1 anytime soon?

**Comment by fevangelou** [comment]
We'll probably release 2.7.1 in the coming week.

**Comment by sevenstudio** [comment]
That would be great. Thank you for the info!
