### ISSUE TITLE
Error when create menu item related to tag

### ISSUE THREAD

**Issue by aussama** [getk2/k2#338]
Joomla: 3.5.1
PHP: 5.6.15
K2: 2.70
Strict Standards: Declaration of K2Element::render() should be compatible with JFormField::render($layoutId, $data = Array) in E:\xampp\htdocs\Sitename\administrator\components\com_k2\elements\base.php on line 25
![k2-menu-tag](https://cloud.githubusercontent.com/assets/1626638/16405575/5fba7904-3d11-11e6-96df-747ca831022c.png)

**Comment by fevangelou** [comment]
This should be fixed in K2 v2.7.1 released a few days ago. Can you confirm please?

**Comment by aussama** [comment]
Fixed!
Done
