### ISSUE TITLE
Limitbox dropdown clipping in backend

### ISSUE THREAD

**Issue by esedic** [getk2/k2#340]
Because item list table is wrapped in <div clas="table-responsive">, which has overflow-y: hidden, limitbox dropdown is clipped/truncated, which expected because of a overflow-y: hidden CSS property.

![k2_clip](https://cloud.githubusercontent.com/assets/617590/16713094/c4fe2100-469c-11e6-8b15-36dcbf29e287.png)

One possible solution would be to add position: absolute to <div class="k2LimitBox">

**Comment by kricore** [comment]
Hello,

Are you using the most recent version of the DEV version?
