### ISSUE TITLE
at version k2 2.7.1 not work search and filter

### ISSUE THREAD

**Issue by DEN007** [getk2/k2#346]
at version k2 2.7.1 not work search and filter
![image](https://cloud.githubusercontent.com/assets/592654/17431844/a5ca706e-5b04-11e6-94db-07323b3500da.png)

**Comment by fevangelou** [comment]
Works fine for me, since I tested as part of a security patch I implemented. Example: http://jmp.sh/7yYg6b8

**Comment by DEN007** [comment]
I no longer work after the update search. I installed the new Joomla and it just does not work, try on a new Joomla. (Version 3.6.0)

**Comment by fevangelou** [comment]
You're searching in Cyrillic right?

**Comment by DEN007** [comment]
Try installing a clean Joomla 3.6.0 and K2 and the problem is played back.

**Comment by fevangelou** [comment]
The problem comes from filtering the string you input for search which is in non-latin characters as I see. I will issue version 2.7.2 today or tomorrow fixing the issue and in the process, I have improved search dramatically.

**Comment by DEN007** [comment]
Thank you!
