### ISSUE TITLE
Add parameter for turning off Magific Popup

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#349]
This is something I'd requested previously for squeezebox. 

At this juncture, many templates have a built in modal function - including anything that uses bootstrap.

We can already turn off jQuery and K2 css - because the K2 developers rightly suppose that front end developers who are using template overrides will want a greater degree of control over the layout.

It only stands to reason that we'd want control over which modal system we use. The ability to turn off Magnific in the K2 parameters would be most welcome.

**Comment by fevangelou** [comment]
Isn't it simpler to just use a different class in your K2 overrides?

**Comment by kricore** [comment]
I think Kelsey has a point here, since 3rd party templates might (and some do) contain different modals and our modal scripts are still being loaded even if they are not being used.

**Comment by fevangelou** [comment]
Magnific Popup is utilised for frontend editing and it used in extra fields (on certain types). It's only loaded in the item view and only when needed (either for the image modal or the extra fields) for non logged in users.

An option to NOT load Magnific Popup in the item view only makes sense for the image modal only.

**Comment by kbrookes** [comment]
I didn't realise about extra fields, this might not be the place, but can
you elaborate on its use in that context?

Unless it's requested specifically, and it never has been yet, I also strip
out all the front end editing code from the overrides.
