### ISSUE TITLE
Cannot use named anchors as targets for custom links in mod_k2_content

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#350]
When using the Custom Link option in mod_k2_content, anything other than using the dropdown to select a menu fails to create a valid link.

For example here is an example of the settings with an external URL:

https://www.dropbox.com/s/6ba26qzrb3o9jvc/Screenshot%202016-08-16%2015.49.35.png?dl=0

The result:

`<a class="moduleCustomLink" href="/index.php?#section-below=&amp;Itemid=136" title="TEST">TEST</a>`

This is even when the manual link is created after having previously saved a menu item. 

There is also no method to remove the selection of a menu item if it needs to be replaced by a custom URL.

**Comment by fevangelou** [comment]
Thanks for letting us know. Fixed in https://github.com/getk2/k2/commit/aacec290d3e0cab75a2dbe1b0eec65227aa99565 - use the GitHub zip file to fix it now on your site. It will be part of 2.7.2 stable out in a few days.
