### ISSUE TITLE
SIGPro pushing images into introtext, even without K2 Plugins present

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#352]
I've got something I really don't understand happening here.

Even when the entirety of item.php is as follows:

`<?php
/**
 * @version    2.7.x
 * @package    K2
 * @author     JoomlaWorks http://www.joomlaworks.net
 * @copyright  Copyright (c) 2006 - 2016 JoomlaWorks Ltd. All rights reserved.
 * @license    GNU/GPL license: http://www.gnu.org/copyleft/gpl.html
 */

// no direct access
defined('_JEXEC') or die;

?>

<div class="examplIntoText">
<?php echo $this->item->introtext; ?>
</div>`

I'm getting not the intro text (which is turned on in both item and category parameters), but the SIGPro gallery intended for that item:

https://www.dropbox.com/s/0oyhn1n0pymtebg/Screenshot%202016-08-18%2014.31.10.png?dl=0

Which is very, very odd.

The 'real' layout has a position for the gallery, and it appears there as it's intended.

There's no content plugins in the introtext:

https://www.dropbox.com/s/5vyomep8voca8m3/Screenshot%202016-08-18%2014.34.34.png?dl=0

**Comment by kricore** [comment]
Can you take a look at the db's table?
What does <?php var_dump($this->item); ?> produce?

**Comment by kbrookes** [comment]
I'll just post the relevant section of the var_dump, let me know if more would be useful:

`object(stdClass)#627 (74) {
  ["id"]=>
  string(4) "1133"
  ["title"]=>
  string(48) "residential-21-bennett-street-west-ryde-10262741"
  ["alias"]=>
  string(48) "residential-21-bennett-street-west-ryde-10262741"
  ["catid"]=>
  string(1) "3"
  ["published"]=>
  string(1) "1"
  ["introtext"]=>
  string(5177) "





	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/21846-Kitchen2-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_21846-kitchen2-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/22581-LivingRoom-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_22581-livingroom-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/23282-Bathroom-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_23282-bathroom-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/23349-Bathtub-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_23349-bathtub-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/23422-DiningRoom2-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_23422-diningroom2-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/23629-Staircase-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_23629-staircase-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/24505-DiningRoom1-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_24505-diningroom1-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/26570-Pool1-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_26570-pool1-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/32092-Pool2-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_32092-pool2-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/580-Shower-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_580-shower-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/607-BathroomSink-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_607-bathroomsink-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/6991-Kitchen1-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_6991-kitchen1-grea.jpg');"></div>
				</a>
	</div>
	<div class="propertyGalThumb col-xs-6 col-sm-4 col-md-4 col-lg-4 col-xl-3">
		<a href="/media/k2/galleries/1133/7746-KitchenSink-GREA.jpg"  class="sigProLink magnificpopup" rel="magnificpopup[mainGal]" target="_blank">
					<div class="propertyGalThumbContainer" style="background-image:url('/cache/jw_sigpro/jwsigpro_cache_b1b2f987ab_7746-kitchensink-grea.jpg');"></div>
				</a>
	</div>



"
  ["fulltext"]=>
  string(1145) "First time offered from new this palatial haven of luxury and custom design; this exceptional family residence built by Alkira Homes and offering absolute comfort, tranquility and leisure. Designed to include all the bells and whistles, with the highest level of finishes and fittings, there is nothing left to want in this stunning home. Nestled in a peaceful cul-de-sac in a sought-after location close to the heart of West Ryde, this family home is perfect for growing families, extended families, busy executives.`


And yet the DB for the item looks exactly like I'd expect:

https://www.dropbox.com/s/qbgi0yyh70cmbmi/Screenshot%202016-08-20%2010.35.21.png?dl=0

**Comment by kbrookes** [comment]
I've also just noticed that the same thing occurs on category_item.php as well.

**Comment by kbrookes** [comment]
We can close this now. We've discovered it's being caused by the UALayout plugin.

Details here: https://github.com/renekreijveld/UserAgentDetector/issues/7
