### ISSUE TITLE
Tag Drag & Drop Ordering

### ISSUE THREAD

**Issue by heyjoecampbell** [getk2/k2#353]
It would be ideal if the Item Edit Page offered drag & drop ordering functionality. 

This would provide the opportunity to better control how K2 Tags are displayed.

**Comment by kricore** [comment]
I think this is a valid request. 
This is an override of the item's form -> https://gist.github.com/kricore/6d969dd9638eced20951b0006875e927 where J! 3's native sortable script has been added. 

Simply reordering the DOM seems to do the trick.

**Comment by kricore** [comment]
The altered file is: https://github.com/getk2/k2/blob/master/administrator/components/com_k2/views/item/tmpl/default.php but it should be treated as an override at this point.
