### ISSUE TITLE
k2 2.7 backend filter not working with Chinese characters

### ISSUE THREAD

**Issue by newjie** [getk2/k2#355]
Screen recording: http://weiwei-tv.com/scroll2.php

As you can see from the video, on backend's item list, when trying to filter the items with any Chinese character, all items will show up in the result. Meanwhile, Joomla article list's filter works fine with Chinese characters.

I have encountered this problem on all of my sites built with k2 2.7, on other sites where the k2 version is still earlier than 2.6.9, there is no problem.

**Comment by kricore** [comment]
Hello Newje,

Please try the latest build of this repo.
It has already been resolved.

**Comment by newjie** [comment]
@kricore Where is the build?

**Comment by fevangelou** [comment]
Use this: https://github.com/getk2/k2/archive/master.zip

**Comment by newjie** [comment]
Thank you that works. I wonder when this will be put in the official release?
