### ISSUE TITLE
Random Order Pagination

### ISSUE THREAD

**Issue by kricore** [getk2/k2#356]
The items (being randomly loaded) appear multiple times.

Sauce here:
http://www.joomlaworks.net/forum/k2-en/46526-k2-random-order-pagination

**Comment by kavadas** [comment]
This is how SQL random sorting works. There is nothing we can do about it. For sites with a few items we could load all of them at once, but i don't think this is something we need to add in K2.

**Comment by heyjoecampbell** [comment]
I recommend either the removal of "random" from list ordering options or provide details of its limitations.

**Comment by PixelPerfectCreative** [comment]
My client has 50 K2 items in a category called "projects". They only show 6 items per page. They would like these items to be in a random order so their users always see the projects in a different order when they visit the site. However, when the user clicks to go to page 2, 3, 4, etc... the K2 items often repeat. I just need a way for the items to only "shuffle" when a user visits the "Projects" page, but then not repeat as they click though the pagination.

**Comment by kavadas** [comment]
@PixelPerfectCreative 

What you can do is load all of the 50 items in a page and then use javascript to split them into pages and create pagination.

**Comment by heyjoecampbell** [comment]
@PixelPerfectCreative

You could create a page and use a module to control the list items.

RAXO All-mode K2 offers an add-on template with pagination functionality:
http://www.raxo.org/additional-templates/all-mode-pagination.html
