### ISSUE TITLE
Length counter for article title

### ISSUE THREAD

**Issue by Winniepooh1** [getk2/k2#365]
This is an enhancement from this topic: http://www.joomlaworks.net/forum/k2-en/46647-integrate-sh404sef-plugin-better

Like in sh404sef it would be nice if there could be a counter for the article title in K2 which shows the current title length and turns red if the optimal length of 65 characters is exceeded. This could help us to find the optimal title.

**Comment by fevangelou** [comment]
I've already implemented a character counter in metadata. The one you refer to, does it primarily relate to the item alias? I'm assuming the title can be anything, but what's important for sh404SEF (since it constructs the actual URL) is to have a limited length for the item alias.

Is that correct?

**Comment by Winniepooh1** [comment]
I'm just referring to the title field like in the com_content. For the title alias it's in my opinion not necessary.

**Comment by fevangelou** [comment]
The title length doesn't matter, it's the title alias that matters to sh404SEF I think. I could be wrong. Perhaps @shumisha can add his thoughts on this.

**Comment by weeblr** [comment]
@fevangelou 

> The title length doesn't matter,

The title lenght is the only thing that matters, in terms of SEO. @Winniepooh1 is referring to the actual item title. This is what should have a limited length (usually 45 to 70 chars, although technically it's not the character counts that matters).

This is not used at all for URL building, but is a basic SEO thing to do for page titles. We add a character counter on the Joomla content editor page title field, and @Winniepooh1 would like to have something like that in K2 as well.

Cheers

**Comment by Winniepooh1** [comment]
I didn't knew that the counter in com_content is provided by sh404sef. I thought it's a built in function by joomla. The integration of the counter in the next version of K2 would be cool.

**Comment by weeblr** [comment]
It's definitely not a standard feature of joomla! we provide the title and description counters, both in the backend and on the front end.

Rgds

**Comment by fevangelou** [comment]
If that's the case, then we could add it as a feature, much like the character counter I added in v2.8.0 for the meta description block. To be implemented in K2 v2.8.1 or 2.9.0.
