### ISSUE TITLE
Add srcset as option to mod_k2_content

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#368]
At present we can't use srcset with mod_k2_content because we're required to select a single image size. 

For those of us trying to optimise for various viewports it means either having extremely low-res images show up on large screens or using mobile detection plugins and having multiple versions of the same module loaded, each for different screen sizes.

What would be a great way around it that would maintain existing compatibility and user expectations would be to have the existing size options AND a srcset option.

**Comment by williamconifer** [comment]
srcset does work with the latest version of mod_k2_content. Here is code I use.

<img src="<?php echo $item->image; ?>" alt="<?php if(!empty($item->image_caption)) echo K2HelperUtilities::cleanHtml($item->image_caption); else echo K2HelperUtilities::cleanHtml($item->title); ?>" sizes="(min-width:1500px) 2500px,(min-width:1200px)  1500px,(min-width:768px)  1200px,(min-width:481px)  768px,452px" srcset="<?php echo $item->imageXSmall; ?> 481w,<?php echo $item->imageSmall; ?> 768w,<?php echo $item->imageMedium; ?> 1200w,<?php echo $item->imageLarge; ?> 1500w,<?php echo $item->imageXLarge; ?> 2500w" />

**Comment by kbrookes** [comment]
Awesome William, thanks. I was under the impression that we couldn't access $item->image? in modules, but that's great news.
