### ISSUE TITLE
Display extrafield (2.7.0 => 2.7.1)

### ISSUE THREAD

**Issue by micker** [getk2/k2#377]
hello i have a big problem
after update to 2.7.1 all my old item aren't display extrafield
if i create new item all is good
i use echo '<pre>' . print_r($this->item->extraFields , true) . '</pre>';
old item => nothing
new item => array ...
other behavior all count item in subecategory print 0 only categorie with new item print number ...
i checked extra_fields columns in k2_items table value is in ...
i don't understand why
thanks for any help

**Comment by micker** [comment]
if i downgrade to 2.7.0 field are display

**Comment by micker** [comment]
template code is the same (2.7.0 -> 2.7.1 no change)
thas not a solution i think any idea ?

**Comment by fevangelou** [comment]
Could your issue be related with this? https://www.robertwent.com/blog/fixing-json-data-errors-after-updating-to-joomla-3-6-3/
