### ISSUE TITLE
Changing image size has no effect on existing images

### ISSUE THREAD

**Issue by smehrbrodt** [getk2/k2#378]
When changing an image size, e.g. "extra large" to 2000px, this has no effect on existing images.

They should be invalidated and regenerated on the next request.

**Comment by fevangelou** [comment]
This process would kill a website with millions of page views per month.

Try this instead: https://github.com/rdeutz/rebuildK2imageCache

**Comment by fevangelou** [comment]
There's also this one: http://styleware.eu/store/item/38-mass-resize-of-k2-images-including-crop
