### ISSUE TITLE
Warning about wrong path of mod_k2_content template file

### ISSUE THREAD

**Issue by baijianpeng** [getk2/k2#379]
Today I am testing K2 v2.7.2 Dev version on an existing Joomla 3.6.5 installation, which had already installed K2 old version. I installed K2 v2.7.2 over this old version and updated it to 2.7.2 .

Then when I view the frontend homepage which contains several modules set up by mod_k2_content, the page shown up as blank page with following error message:

> Notice: Trying to get property of non-object in D:\xampp\htdocs\joomla\modules\mod_k2_content\mod_k2_content.php on line 50
> 
> Warning: require(D:\xampp\htdocs\joomla/modules/mod_k2_content/tmpl/default.php): failed to open stream: No such file or directory in D:\xampp\htdocs\joomla\modules\mod_k2_content\mod_k2_content.php on line 74
> 
> Fatal error: require(): Failed opening required 'D:\xampp\htdocs\joomla/modules/mod_k2_content/tmpl/default.php' (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\joomla\modules\mod_k2_content\mod_k2_content.php on line 74
> 

I know nothing about PHP programming. But form above message, it seems that the file mod_k2_content.php was trying to read the file "/modules/mod_k2_content/tmpl/default.php". However, in fact, this path is wrong, because there is an Extra folder named "Default", so the correct path should be:

`/modules/mod_k2_content/tmpl/Default/default.php`

Why the  file mod_k2_content.php skipped that folder "Default"? Is this a bug? Or something wrong in my K2 installation?

Hope someone will point out the key of this problem.

Thank you.

**Comment by fevangelou** [comment]
Open up the related module instance, make sure it shows "Default" as the sub-template folder and just hit save. Do you still see the issue?

Additionally, what are your Windows & XAMPP versions?

**Comment by fevangelou** [comment]
Good to have you back, by the way...

I remember you were one of the first folks to send me feedback on AllVideos waaaay back in 2006 as well as a Chinese translation :)

**Comment by baijianpeng** [comment]
hi Fotis, glad to see you again. Thank you for this great project.

Please close this issue (or delete it), since this happened on a Joomla with old K2 versions and with some weird HTML overrides, I can not sure this is related to K2 itself.

Thank you.
