### ISSUE TITLE
feature request: "length(characters) limit" option for item title in K2 Content Module

### ISSUE THREAD

**Issue by baijianpeng** [getk2/k2#380]
I would like to use K2 Content Module as a news list module on frontpage, and use 3 of this kind of modules side by side in the same horizontal position on the template.

However, since some news has very long title, these titles will wrap and occupy **TWO LINES** of page space on the module, while other shorter titles only occupy a single line.

Since the "long" or "short" of article title is random, so the result is: the height of the module will vary now and then. And the worse is, those 3 modules therefore will have DIFFERENT height! This makes the page layout looks very ugly!

So I hope there will be a new option in the parameters of this module:

**Title length limit: xxxx  Characters**

Then I can control the module height by item count, since each item always occupy only one single line. And this will make multiple modules in the same horizontal line have the same height.

Thank you.

**Comment by fevangelou** [comment]
Will be added in the upcoming K2 Pro Suite release.
