### ISSUE TITLE
feature request: new filter by article ID number on backend article list

### ISSUE THREAD

**Issue by baijianpeng** [getk2/k2#383]
If a K2 instalation has more than 20,000 articles, how to quickly find the article with ID "20184"?

My suggestion is: please add a new filter method by "article ID number". Maybe you think a new filter inputbox will occupy exra page space, well, you don't need to add a new inputbox there, just use the "text filter" inputbox. If the user input a pure number, search that number in both article Title and article ID number.

If you want to make a specific ID number filter, maybe just a new rule can solve this: let the user input "id=20184" to find article by its ID.

Thank you.

**Comment by williamconifer** [comment]
+1

**Comment by fevangelou** [comment]
We'll probably follow the pattern "id:12345" as that's also used in other components as well.
