### ISSUE TITLE
elFinder updated and secure?

### ISSUE THREAD

**Issue by pepperstreet** [getk2/k2#386]
Hello, I heard about the security issues in ElFinder 2.0 RC1. 
I have also noticed your hint about an update to 2.1.14 ...  

But in latest K2 v2.7.1 release and current repository files, I still read the older elFinder version number in the header! Just a wrong header info, or does it still need the important file update?  

Something to worry about?
Thanks in advance.

**Comment by fevangelou** [comment]
K2 v2.8.0 (dev) already has a newer version of elFinder but when it'll be officially released, I'll make sure to update elFinder to the newest one.
