### ISSUE TITLE
Can not post after upgrading to Joomla 3.7

### ISSUE THREAD

**Issue by AyelGoth** [getk2/k2#389]
After updating to Joomla 3.7, the K2 component does not allow me to publish articles. When you try to save the article, it takes too long and a blank screen appears.

**Comment by balina100** [comment]
I have that same problem. Help please. Especially if there is an image upload, it is not registered. The blank screen is exiting.

**Comment by Simon-Davies** [comment]
I'm also having this issue. I thought it was a Joomla 3.7 issue so created an issue on the Joomla github.

For me it will sit loading trying to save a long blog post I've updated and then redirect me to www.mydomain.com/administrator/index.php?

**Comment by fevangelou** [comment]
Do you have any third-party system or K2 plugins that could be crashing? Try switching error reporting to "maximum" in Global Configuration and check again for the error that should appear instead of the blank screen.

In our tests prior to the release of J3.7, we did not notice any issues with the same process. Actually the only thing I missed was the calendar issue (no time rendered) but that's a bug in Joomla and we've sent a patch for that already.

**Comment by balina100** [comment]
Thanks Fevangelou. It only records when we add text.. But if there is a picture, it does not record and redirect to ablank screen url : www.mysite.com/administrator/index.php

**Comment by Simon-Davies** [comment]
Heya guys I created am issue on the Joomla github and got this reply:

Maybe it is related to this issue #15673 . The solution for now is restore the file libraries/joomla/filter/input.php from Joomla 3.6.5 version as mentioned by other users

**Comment by balina100** [comment]
Simon-Davies Thank you so much. The problem has been solved by changing the input.php file.

**Comment by Simon-Davies** [comment]
Always here to help :)

**Comment by Simon-Davies** [comment]
If you like Ethical Hacking check out my website's blog https://www.engetsu-consulting.com/blog

**Comment by balina100** [comment]
I visit your site now.

**Comment by AyelGoth** [comment]
In the error reports I get the following message:

Fatal error: Maximum execution time of 90 seconds exceeded in /var/www/html/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 41

I did a test, I created a publication that contained no accents, no quotes. The item was saved correctly. I created another article that contained special characters, quotes, accents, I can not keep. I think the problem has something to do with UTF8.

**Comment by Simon-Davies** [comment]
You could very well be correct as recently I used Admin Tools to change my database collation to UTF8

**Comment by fevangelou** [comment]
Is this resolved with the newest 3.7.x releases for you guys?

@AyelGoth I assume php-mbstring is installed on your server...

**Comment by Simon-Davies** [comment]
For me it has been resolved after updating to the latest Joomla builds.

**Comment by fevangelou** [comment]
@Simon-Davies That's good to know.

**Comment by Simon-Davies** [comment]
I'm assuming this can be closed now

**Comment by fevangelou** [comment]
Thank you.
