### ISSUE TITLE
Feature Request: K2 Tools (Search Module) Article Word Limit

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2#392]
Would it be possible to add a word limit for articles displayed when using the K2 Tools (Search Module). 

So exactly how you can do it in Category view with a word limit and Read More.

At present whole articles are displayed resulting in a lot of scrolling to find what you are searching for.

**Comment by fevangelou** [comment]
You're absolutely right - this should be in all itemlist views (user, tag, search etc.).

To be added in v2.8.0.
