### ISSUE TITLE
Feature Request: Add LinkedIn button to Social buttons

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2#393]
At present there is a Twitter, Facebook and Google+ button for Social buttons. Would it be possible to add a LinkedIn one. I know we can manually do it but it would be nice to have it built into the core of K2 and all the buttons using the same style.

Also with the Social buttons a more modern Square/Rounded look would be nice.

**Comment by fevangelou** [comment]
Social sharing needs an overhaul to be honest. I'm leaning towards ditching the native share buttons and going with something like this: https://simplesharingbuttons.com/

Moreover, offer an option to select which social networks to show.

In that case, I don't see why LinkedIn couldn't be added.

Thanks.
