### ISSUE TITLE
Cannot create K2 'item' menu item

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#395]
I'm on K2 2.8.0 (upgraded to fix the issue in mod_k2_content with custom links not working) and Joomla 3.7.2.

When creating a new K2 'item' menu item, items are not selectable in the item list. Additionally the red 'close' button does not work. The modal close button does.

At present it's impossible to create menu links to K2 items.

I've attempted on both Firefox and Chrome on MacOs Sierra.

Video of issue: https://www.dropbox.com/s/vb0bh2fgc1k847s/k2-item-error.mov?dl=0

**Comment by fevangelou** [comment]
This is still worked on as part of a refresh on all these content selection modals. I'll make sure to fix it within the next 2 days.

**Comment by kbrookes** [comment]
Thanks Fotis, that's great.

**Comment by witraze** [comment]
Will be grateful for the fix as after upgrade menu items to K2 items are broken. 

Thanks Tomek

**Comment by ronnyvanderborght** [comment]
Can anyone confirm that this has been fixed ?

**Comment by lucertola** [comment]
Installed yesterday 2.8. It does not work yet. If you create new menu items, it's a real problem

**Comment by bugsmafia** [comment]
+1 not work yet.

**Comment by manwlios** [comment]
Any update here? This is a serius drawback now. Thanks in advance.

**Comment by kbrookes** [comment]
Yeah, this is becoming hugely problematic for me as well.

I needed the upgrade to fix an issue in mod_k2_content, but it's crippled menu creation.

**Comment by fevangelou** [comment]
The issue will be resolved within the coming day - sorry for the delay

**Comment by kbrookes** [comment]
Thanks Fotis, that's great.

One of the reasons we're using dev versions on production sites is that we've been told to on the forum.

There were a couple of issues in 2.7.1 that could only be fixed by 2.7.2 - and we were told to use that version. By the time the next site was being developed, 2.7.2 didn't exist and the only option to fix those issues was 2.8... which introduced new ones.

**Comment by fevangelou** [comment]
Fixed.

The modal is now also more informative :)

**Comment by ronnyvanderborght** [comment]
I, for one,  wouldn't mind paying for regular k2 updates and improvements, or to keep it in par with future Joomla releases. If a subscription is the way to keep the product evolving then why not ? Has the whole k2 'pro' concept been ditched ?

**Comment by fevangelou** [comment]
Not at all. In fact, we'll be starting with Pro support in September, then enriching K2 with additional extensions that eventually make up the K2 Pro suite. And starting with v2.8.0 you'll see more releases more often.

**Comment by kbrookes** [comment]
Great news, I'll be interested to see what that entails, but I'll be a subscriber.

Any news on whether K2 Next will continue work or has that been shelved?

**Comment by fevangelou** [comment]
Shelved. It was a great test bed and we had the chance to explore a better & more practical UI (sone concepts ended up even in Joomla's com_content as you may have noticed), but I've decided to take a more future-proof approach for its future development. I'm already doing some tests with vue.js for the UI in the backend but the plan is to rebuild the backend so it's not tied to a certain JS UI library. In other words, if vue.js retires later, I won't have to rebuild everything.

**Comment by kbrookes** [comment]
Thanks Fotis, I very much appreciate the clear answer on this.

**Comment by kbrookes** [comment]
This seems to be broken again for me:

https://www.dropbox.com/s/ss9pig8f5sbzbfq/Screenshot%202017-08-11%2015.51.12.png?dl=0

Modal works, clicking an item immediately closes the modal, but no item is selected.

**Comment by fevangelou** [comment]
It works just fine on my end. See: http://jmp.sh/1HdZXHd

Update to the latest release from GitHub and do a hard-refresh on the page you're working on to purge any existing caches on JS files.

**Comment by kbrookes** [comment]
Yep, you're right.

I had done that already - hard refreshed, the works. 

But just as when a family member calls over their tech-savvy relative to deal with a computer problem, all it took was a glance from you and everything fell into place ;)

**Comment by fevangelou** [comment]
Hahaha!
