### ISSUE TITLE
Cannot select items in mod_k2_content "select specific content"

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#397]
Same issue as #395 except in mod_k2_content.

Using K2 2.8, Joomla 3.7.2 you can't select items for inclusion in mod_k2_content using 'select specific items'.

**Comment by fevangelou** [comment]
I think this is a JS related issue - this was changed some commits ago but if the version was the same for you, perhaps cache-busting did not kick in.

Re-install the Github copy and try it again using a private window this time.

**Comment by fevangelou** [comment]
Can you confirm?

**Comment by kbrookes** [comment]
Hi Fotis, apologies for the late reply, I've been slammed.

That fixes the issue thank you very much.

**Comment by fevangelou** [comment]
Great :)
