### ISSUE TITLE
Conflict with Advanced Module Manager & mod_k2_content in admin

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#398]
Regular Labs Advanced Module Manager is almost a requirement for complex K2 sites, but K2 2.8 and AMM on Joomla 3.7.2 is somewhat broken in the admin panel.

There's a js conflict in the console with k2.js:

"Uncaught TypeError: $(...).sortable is not a function"

It causes the module tabs (assignments, permissions, etc) on mod_k2_content to be set to display:hidden and all parameters have lost their styles.

This isn't a problem with previous versions of K2 or with non-k2 modules in 3.7.2. AMM seems to be fine in non-k2 contexts.

**Comment by ronnyvanderborght** [comment]
I totality agree.

**Comment by fevangelou** [comment]
I think the component (AMM) is loading on its own interface/container and I do checks on where to run any JS scripts coming from K2. Thus jQueryUI is not loaded and so you get that JS error. Do you mind telling me what is the system name of the component to add an exception? E.g. com_advancedmodulemanager?

**Comment by fevangelou** [comment]
(BTW I was on a work leave for around a month - things are now back to normal for development)

**Comment by ronnyvanderborght** [comment]
Hi Fotis,
That should be: com_advancedmodules

**Comment by kbrookes** [comment]
Hi Fotis, sorry for the late reply, can confirm that's com_advancedmodules as Ronny said.

**Comment by fevangelou** [comment]
Fixed in this commit: https://github.com/getk2/k2/commit/9c35d48fb8427804e6f9868eb98018dbcae69575
