### ISSUE TITLE
No use of content triggers

### ISSUE THREAD

**Issue by regularlabs** [getk2/k2#399]
For an extension of mine I rely on the Joomla content triggers (`onContentAfterSave`, `onContentAfterDelete`, `onContentChangeState`) to be able to store extra information.
However, K2 does not seem to use these event triggers anywhere. Meaning I am not able to implement support for K2 for this.
Please add the content triggers in the appropriate places...

**Comment by regularlabs** [comment]
Also, When an item gets trashed, it now triggers the `onFinderChangeState` event. However, this just gives info about the publish 1/0 state. That event gives no information about the fact that it gets trashed.

And also, when a category gets trashed, it also trashes the underlying items. But there is no event trigger at all for these items.

**Comment by nicksavov** [comment]
+1 for adding the content triggers

**Comment by fevangelou** [comment]
@regularlabs Which extension are you referring to if you don't mind me asking?

**Comment by regularlabs** [comment]
Better Trash: https://www.regularlabs.com/extensions/bettertrash

**Comment by fevangelou** [comment]
As you know, we extremely rarely change the DB schema in K2. In 8+ years of K2, we've done 5-6 changes, with 2 of them related to making K2 InnoDB compatible.

Wouldn't it be simpler to just query K2's tables and get the data you want? E.g. display trashed items and categories or delete either/or...

**Comment by regularlabs** [comment]
This is about plugins getting triggered when stuff gets done.
I need my plugin to do stuff the moment an item gets trashed or deleted or other status change.
Currently my plugin, nor any other, can do stuff in the process of creating K2 items and status changes thereof.

The solution is to simply add the necessary triggers to the code of K2.

**Comment by fevangelou** [comment]
Since K2 is free as you know and I suppose your plans to support K2 are for the Pro version of your extension, plus I already have a huge list of tasks for K2 v2.8.0 and 2.9.0, be my guest and send a PR with the changes you like. I'll review them and if nothing breaks, I'd be happy to apply the PR.

**Comment by regularlabs** [comment]
Done: #403

**Comment by fevangelou** [comment]
Accepted, thank you.

**Comment by fevangelou** [comment]
BTW, I added some missing plugin group imports.

**Comment by regularlabs** [comment]
Cool :)

**Comment by nicksavov** [comment]
Wow, thank you Peter and Fotis!

Cheers,

**Comment by agerix** [comment]
Thx from Better Trash and K2 user ;)
