### ISSUE TITLE
Can't turn off "Control K2 User Profile display for users with no items"

### ISSUE THREAD

**Issue by witraze** [getk2/k2#400]
Hi
Joomla v. 3.7.3 and K2 v 2,8.0 (developer version dated from July 2017) the option: "Control K2 User Profile display for users with no items" is not working properly - can't display Pages of K2 Users with no items (switch is in proper position "Turned off".)
regards Tomek

**Comment by fevangelou** [comment]
It should be in "Enabled" if you wish to show user profiles for users that DO NOT have items.

**Comment by witraze** [comment]
Thank you for explanation indeed. My fault – it is working now :)  

Regards Tomek
