### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#402]
I'm now at the point where most clients ask about version control at some point. 

Most of them have worked with CMS' before and it's becoming a bit of a stumbling block to developing in K2 that I have to articulate before development starts.

It'd be great if this got added in at some point.

**Comment by williamconifer** [comment]
Will content versioning show up in 2.9.1 or K2 Pro? This is a feature I have been waiting on for over 5 years.

**Comment by kbrookes** [comment]
Thanks for commenting on this @williamconifer - K2 is still the absolute best content tool for Joomla. Every now and then I try building in native Joomla and it's just not a patch on K2...

Except as I said in my original comment, 2 years later, ALL of my clients are now surprised that this otherwise incredible system  doesn't support versioning. 

At some point soon, it's going to go from surprise and a bit of disappointment to demanding.

**Comment by kbrookes** [comment]
I'd love to know if this is on the cards for K2 future development.
