### ISSUE TITLE
No modal on select author K2 item

### ISSUE THREAD

**Issue by mdraghici1503** [getk2/k2#404]
When I try to change the Author of a K2 item - there is no modal pop-up. Instead the table with all users is opened in the main browser page and on selecting an item nothing happens. I am using the latest K2 from the repository and Joomla 3.7.4

**Comment by fevangelou** [comment]
Have you tried installing the latest dev copy from GitHub? https://github.com/getk2/k2/archive/master.zip

**Comment by mdraghici1503** [comment]
yes, it's the latest version from the repository. I just uploaded it again to make sure but it still has the same behaviour.

**Comment by fevangelou** [comment]
It's working just fine for me. The fact that you see the full users table means that there is some sort of JS error that breaks the modal. Can you have a look what the Console in your browser's dev tools shows? The JS error could come from some 3rd party system or K2 plugin...

**Comment by mdraghici1503** [comment]
You are correct - it seems there is an error from the K2store extension. Any ideas?

`k2storejqui.js:16 Uncaught TypeError: this.element.uniqueId is not a function
    at e.(anonymous function).(anonymous function)._create (http://.../media/k2store/js/k2storejqui.js:16:65610)`

**Comment by mdraghici1503** [comment]
[Solved] - went into K2store and in options selected to Load jQuery only for the frontend.

**Comment by fevangelou** [comment]
It was loading a slightly newer version of jQueryUI (v1.9.2) and that was causing conflicts. I have already updated jQueryUI to the latest release (v1.12.1) in other parts of K2 v2.8.0 and the item edit form is the last part that requires adaptation for that new release, as it still uses jQueryUI v1.8.24 for the tabs and some other functionality.
