### ISSUE TITLE
"Do not create item link"

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#406]
I use K2 in a way where I frequently have items that are only ever shown in a category-item context or a module context, but are never deliberately linked to. 

Even when I have title, image and readmore links disabled, and have actively removed all links to the item via template override, the item pages often show up in search results anyway.

In many of these cases, the actual item is a hinderance because I then have to manually redirect it via .htaccess.

I'm not sure if it's even possible, but it'd be awesome if those item view url parameters were never created.

**Comment by fevangelou** [comment]
You can't hide something public from search results. That was never the intention either way unless ACL is in force. Why would this be a problem for you in the first place?

(if you refer to Google search results, Google can pick up pages from e.g. your client's or your browsing history and add to its index, unless a noindex meta is provided with the item(s))

**Comment by fevangelou** [comment]
BTW, we don't create any item links. It's possible that as I said, either Google picked the URLs up or some Finder/Search plugin revealed the items for some visitor in which case, Google picked them up as well if they were logged in on Google.

**Comment by kbrookes** [comment]
I get how this seems odd.

An example would be an FAQ page.

Clients regularly screw up an FAQ page formatted by javascript that relies on them getting the right headings and paragraph elements.

Instead I create an FAQ category and the only display of the items in that category is in the category view, where they're (usually) presented as an FAQ accordion.

Simple for the client to manage (add a new item to the FAQ category, title becomes the question, body becomes the answer), limited opportunities for them screwing it up.

But do I want an individual FAQ item to be accessible as a page?

No.

But somehow these pages are regularly revealed (no idea how, because there's no links on the titles usually no method to access them).

So perhaps ACL is the way? My 'ideal world' scenario would be able to stop the item view ever being accessible for these types of categories.

**Comment by fevangelou** [comment]
There's always a way to get to items. Either via search, tags or of course menu items. If you've made sure 2 & 3 are handled, then you could disable the K2 search plugin. Of course this seems like an interesting feature for the upcoming K2 Pro Suite. A specialized search plugin for K2 that searches on either specific categories only or the reverse, all but a few. How's that sound?

**Comment by kbrookes** [comment]
Actually, that would be awesome already.

I have multiple sites where they wanted to restrict search to specific categories anyway.

Speaking of that search plugin - if it integrated with Joomla smart search it'd be great. We were having trouble with the relevancy of results on a client site with K2 Tools search and found switching to the core Joomla Smart Search (indexing K2 items) extremely effective at producing good results.

**Comment by fevangelou** [comment]
There are plugins for "normal" and "smart" (aka finder) search already - but they are not built to only search specific content. That could change of course. Added in my K2 Pro notes :)

**Comment by kbrookes** [comment]
Awesome. I'd have subscribed to Pro no matter what. K2 has been the bedrock of my dev work for many years now. I have a vested interest in it continuing.

BTW - another couple of things I'd love to see in a pro version:

#1 - Versioning. This is probably the #1 thing that now causes post-launch dissatisfaction for clients, to the point where I have to flag it before we started.

#2 - Sub-category pattern module
This is a weird one, and most people I've discussed it with don't get it at all. I would use it constantly, but I'm willing to admit my use-case is odd.

An example is best:

https://odemanagement.com/speakers/michael-mcqueen

The category structure looks like this:

- SPEAKERS
-- SPEAKER NAME (in this case Michael McQueen)
---- TOPICS
---- TESTIMONIALS
---- PRODUCTS

The article itself is named for the speaker as well and is in the SPEAKER NAME category.

Articles in the TOPICS, TESTIMONIALS and PRODUCTS categories feed those positions on the page.

'Read Me' is driven by Authorship on the news page. The Twitter feed and PDF Me button are driven by ExtraFields. Hero image is the image tab, galleries by SIGPro. Videos are pulled in in the override based on tags from the video server.

But it's the Topics, Testimonials and Products I'm talking about here. To create this site, I need to create a module for each of those categories, for each speaker on the site. In this case 93 modules to handle layout of these pages with dynamic content that can easily be updated by the client.

I'd love it if I could drive all of that with just 3 modules.

There are two modules which currently come close to offering this:

mod_k2_BNR and K2 Split Content.

They allow you to set modules on a page that serve up their content dynamically based on the current item.

I'd like to extend this idea by having the same dynamic-by-item functionality, but where the module is mapped not to an item, but to a pattern of child category based on the item's parent category.

Weird, I know. Hugely powerful tho. :)
