### ISSUE TITLE
Upgrade to K2 2.8.0 and got PHP notice

### ISSUE THREAD

**Issue by mgscreativa** [getk2/k2#408]
Hi! Just upgraded to K2 2.8.0 and I'm getting this PHP notice:

> ( ! ) Notice: Trying to get property of non-object in components/com_k2/views/itemlist/view.html.php on line 651

**PHP v5.6.31**

Debugging the code, turns out that $default got null, and $default should return default menu item from line : **$default = $menu->getDefault();**

I solved by adding a **is_object($default)** check to line 651, but seems my site is multiland (spa, eng), I think $menu->getDefault() gets confused and returns null...

Please advise!

thanks! 

```
		// Feed link
		$config = JFactory::getConfig();
		$menu = $application->getMenu();
		$default = $menu->getDefault();
		$active = $menu->getActive();
		if ($task == 'tag')
		{
			$link = K2HelperRoute::getTagRoute(JRequest::getVar('tag'));
		}
		else
		{
			$link = '';
		}
		$sef = K2_JVERSION == '30' ? $config->get('sef') : $config->getValue('config.sef');
		if (!is_null($active) && is_object($default) && $active->id == $default->id && $sef)
		{
			$link .= '&Itemid='.$active->id.'&format=feed&limitstart=';
		}
		else
		{
			$link .= '&format=feed&limitstart=';
		}
```

**Comment by Robdebert** [comment]
You may always hide "notices" from phps error_reporting output.
Mostly these message do only appear when a variable was not set, but should now be used. PHP can handle these situations quite well, although it is a good practice to "set" a variable before or test "if (isset())" and check the datatype.

But as a workaround, you can exlcude E_NOTICE from error_reporting: http://www.bx.com.au/tools/ultimate-php-error-reporting-wizard
