### ISSUE TITLE
Extra fields hidden in item edit 2.8.0

### ISSUE THREAD

**Issue by manwlios** [getk2/k2#409]
Hello there!

After the update to 2.8.0 tha extra fields area is hidden (see screenshot)
![2017-08-19 12 01 49](https://user-images.githubusercontent.com/14349063/29477592-9fd6b2f2-8471-11e7-8b7f-0f723b02058d.png)

After inspecting, i found out that the div has a style "display:none;" and also i see the following error on console.
![2017-08-19 12 03 53](https://user-images.githubusercontent.com/14349063/29477649-ecd53a60-8471-11e7-985c-c71e54849735.png)

thanks!

**Comment by fevangelou** [comment]
I see a reference for the Joomla calendar widget but K2 does not use that anymore. Please open the K2 extra field (under Extra Fields) and just hit save. Then check again in the item form view to see if you still get the error.

**Comment by manwlios** [comment]
Hello,

i tried to save the field but nothing changed. The extra fields area is still hidden.

**Comment by fevangelou** [comment]
No issue on my end for new extra fields created. http://jmp.sh/0kfGhy2

Can you create a new date field on a group with no other date field and check again? If this doens't work either, perhaps the conflict is coming from somewhere else.

**Comment by manwlios** [comment]
Hi Fotis, you were right. I started playing with the plugins and the plugin that was causing the problem was K2 - JA K2 Filter. After disabling this, the date field works fine. So i'm heading over to Joomlart to report the problem. Thank you :)

**Comment by fevangelou** [comment]
Cool.
