### ISSUE TITLE
Dates modified when you update the K2 Item

### ISSUE THREAD

**Issue by LordRazen** [getk2/k2#411]
Hello, 

I use K2 2.8.0 on Joomla 3.7.4
I recognized that the dates of an item are modified in the wrong way when you update it. The "modified date" is modified correctly, but if you save an item also the "creation date" and the "start publishing" date is updated. This will mess up the content shown in the K2 Content Module if you show the most recent entries. 

![k2 dates](https://user-images.githubusercontent.com/9381368/29594938-a3cce1ec-87b4-11e7-804b-bcee7f7117df.PNG)

Thx for a fix :)

**Comment by fevangelou** [comment]
I'm sorry, but I can't verify the issue. Using Joomla 3.7.5 but I doubt this may be the differentiator.
