### ISSUE TITLE
Itemlist JSON view missing description 

### ISSUE THREAD

**Issue by ChrysaP1024** [getk2/k2#414]
There is a bug in the item list JSON view (file views/itemlist/view.json.php) and as a result the category description is not included in the JSON output

More specifically, the category description is not included in the row variable

Please have a look at lines 135 and 146 and 202-214 and maybe add a line like the following
$row->text = $category->text;
or
$row->description = $category->text;

**Comment by fevangelou** [comment]
Good catch Chrysa, although I used `$category->description` so the output of plugins for that field can be rendered as well. It's already in 2.8.1 dev.

**Comment by fevangelou** [comment]
As an example, check e.g. https://getk2.org/showcase?format=json
