### ISSUE TITLE
Repeatable fields do not work as expected

### ISSUE THREAD

**Issue by afonic** [getk2/k2#417]
Hello,

This thread has captured the problem: http://www.joomlaworks.net/forum/k2-en/45289-problem-with-k2-plugin

The repeatable field inside the K2 view (category view), displays the modal form.

Also, the new Subform form field type does not save correctly (it doesn't save at all).

Any ideas on how to fix this?

**Comment by kricore** [comment]
Hello,

Which repeatable fields are you referring to?
K2 does not offer repeatable fields by default.

**Comment by afonic** [comment]
Hello,

This refers to adding a field in the category page using a plugin (like the Example K2 Plugin). These Joomla fields do not work correctly (repeatable and subform).

Maybe there is no support for them in K2 admin views?

**Comment by fevangelou** [comment]
My guess is our XML field parser does not render these fields because they further encapsulate other fields. Marked as a bug to fix in the next update. I'll update this thread with more info as we resolve the issue.

**Comment by mixahlos** [comment]
Kalispera Foti,
@fevangelou 
Is there any update about when the next release is going to happen ?
Or is any suggestion to temp fix that until the next release ?

Thank you
