### ISSUE TITLE
Extra fields content tab display:none

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#418]
Since the upgrade to 2.8 I'm getting a blank content tab for extra fields on items due to .k2TabsContent > #extraFieldsContainer being set to display:none; inline on the element.

I believe this might be related to the FancyBox error described in [issue 412](url=https://github.com/getk2/k2/issues/412), but that could just be a coincidence.

**Comment by fevangelou** [comment]
Have you tried switching to another popup engine for SIGPro? This CSS code has always been there to assist with the tab effect.

**Comment by kbrookes** [comment]
On the admin side? I just tried switching from LightView to FancyBox - no difference to the Extra Fields tab content element display property.

**Comment by fevangelou** [comment]
I meant switch away from FancyBox in SIGPro, e.g. ColorBox.

**Comment by kricore** [comment]
Are you by any chance using K2 Filter?

**Comment by kbrookes** [comment]
I've tried switching to ColorBox and back to LightView - no change.

I am using JA K2 Filter.

**Comment by kricore** [comment]
Try temporarily disabling K2 Filter, it is known to cause issues with 2.8.
Let me know how it goes.
