### ISSUE TITLE
CKEDITOR is not defined javascript error

### ISSUE THREAD

**Issue by ryandemmer** [getk2/k2#419]
When creating or editing an Item, a _ReferenceError: CKEDITOR is not defined_ javascript error is produced (Firefox)

The error occurs due to line 74 of **plugins/system/k2extrafields/k2extrafields.php**

```javascript
if ( CKEDITOR && CKEDITOR.tools.callHashFunction) {
```

Changing this line to

```javascript
if ( typeof CKEDITOR != 'undefined' && CKEDITOR.tools.callHashFunction) {
```

removes the error.

**Comment by fevangelou** [comment]
Ryan, the plugin you mention is not part of the K2 bundle. :)

**Comment by fevangelou** [comment]
See: https://github.com/getk2/k2/tree/master/plugins/system

**Comment by ryandemmer** [comment]
My apologies! Yes, this plugin appears to be a part of Ark Editor.

No problem then, uninstalling.
