### ISSUE TITLE
K2 2.8 breaks img srcset - malformed path

### ISSUE THREAD

**Issue by williamconifer** [getk2/k2#420]
I have adapted srcset code share by Krikor to responsively display images in my K2 layout overrides. 

**This code worked in K2 2.7.1 - from item.php**
`<img src="<?php echo $this->item->image; ?>" alt="<?php if(!empty($this->item->image_caption)) echo K2HelperUtilities::cleanHtml($this->item->image_caption); else echo K2HelperUtilities::cleanHtml($this->item->title); ?>" sizes="(min-width:960px) 726px,(min-width:768px)  911px,(min-width:481px)  739px,452px" srcset="<?php echo $this->item->imageXSmall; ?> 200w,<?php echo $this->item->imageSmall; ?> 300w,<?php echo $this->item->imageMedium; ?> 500w,<?php echo $this->item->imageLarge; ?> 800w,<?php echo $this->item->imageXLarge; ?> 1200w" />`

**In K2 2.8.0 the same code renders out as such...**
`<img src="/media/k2/items/cache/5734ccbbcc4bd04e97372ff3dad99251_L.jpg" alt="White Pines State Park" sizes="(min-width:960px) 726px,(min-width:768px)  911px,(min-width:481px)  739px,452px" srcset="//media/k2/items/cache/5734ccbbcc4bd04e97372ff3dad99251_XS.jpg 200w,//media/k2/items/cache/5734ccbbcc4bd04e97372ff3dad99251_S.jpg 300w,//media/k2/items/cache/5734ccbbcc4bd04e97372ff3dad99251_M.jpg 500w,//media/k2/items/cache/5734ccbbcc4bd04e97372ff3dad99251_L.jpg 800w,//media/k2/items/cache/5734ccbbcc4bd04e97372ff3dad99251_XL.jpg 1200w" class="">`

Notice the extra leading slashes in the srcset code. If you remove the extra slash the image appears. 

So far I can confirm that this happens in item.php and category_item.php. I am assuming the same fate if used in mod_k2_content.

We are having to hold off updating other large K2 run websites due to this issue.

**Comment by fevangelou** [comment]
If you have a look at the file /components/com_k2/models/item.php where these image variables are constructed, you'll notice there's nothing special there. E.g.

`$item->imageXSmall = JURI::base(true).'/media/k2/items/cache/'.md5("Image".$item->id).'_XS.jpg';`

Unless you're modifying that path elsewhere, e.g. at the top of item.php (in the templates folder), then provided you're at the html root of the site, `JURI::base(true)` should return empty. If it doesn't, check in Joomla's configuration.php if there's something in `public $live_site`.

**Comment by williamconifer** [comment]
Thanks for your reply Fotis. If I am understanding you, you are saying that there is some code in my item.php override or joomla configuration live site that is causing a malformed path. I have tested this premise and this is not true. The joomla configuration.php file is correct. 

To test the override code I did this:
I created a new override item.php file using the default k2 template php code. 
Then I swapped out the img code with the code using img srcset

`<img src="<?php echo $this->item->image; ?>" alt="<?php if(!empty($this->item->image_caption)) echo K2HelperUtilities::cleanHtml($this->item->image_caption); else echo K2HelperUtilities::cleanHtml($this->item->title); ?>" sizes="(min-width:960px) 726px,(min-width:768px)  911px,(min-width:481px)  739px,452px" srcset="<?php echo $this->item->imageXSmall; ?> 200w,<?php echo $this->item->imageSmall; ?> 300w,<?php echo $this->item->imageMedium; ?> 500w,<?php echo $this->item->imageLarge; ?> 800w,<?php echo $this->item->imageXLarge; ?> 1200w" />`

I saved and uploaded. The image would NOT show using my srcset customization in the default template code. The srcset path to the images are malformed, however the src path is not malformed. Please see my first post with a same of the rendered code.  

I also tested this with all SEF/SEO turned off with the same issue. 

Then, in that item.php file which was using the default template code, I removed my srcset code and replaced it with the default img code and the image displayed properly. 

Thus none of my custom code is causing the srcset custom code to fail. Other than the srcset code itself. 

My srcset code was working in the same website when it was K2 2.7.1 in Joomla 3.7.5. When I upgraded to K2 2.8 and Joomla 3.8 the img srcset issue presents itself.

The use of srcset in K2 layout overrides is a huge deal for us for performance and seo reasons. my gut is telling me something is wrong.

**Comment by fevangelou** [comment]
Thing is, we didn't change anything there. Unless JUri::base() is broken in
3.8.0 be (which I doubt). I'll test it on my own and get back to you again
by tomorrow.

Do you mind uploading your entire item.php file so I can use it in my tests?

**Comment by williamconifer** [comment]
Here you go. 
[item - srcset-issue.php.zip](https://github.com/getk2/k2/files/1345389/item.-.srcset-issue.php.zip)

this page uses this override, however since it's live I have to use the non-srcset code for image display
https://www.visitnorthwestillinois.com/trip-ideas/meet-our-regions-namesake.html

**Comment by williamconifer** [comment]
Update on my testing.

I have a Joomla/K2 site in development with a lot of k2 overrides. I am using srcset for any item image displayed in item, item_category or the mod_k2_content pages. The srcset code I use is the same code I posted earlier in this thread.

This site was running K2 ver. 2.8 in Joomla 3.7.5 and the srcset image display was OK. No problems. 
I then updated Joomla to 3.8.0 and the srcset image DID NOT display.

So, relating to srcset, srcset images display fine in K2 2.8 when running in Joomla 3.7.5. BUT the srcset images DO NOT display when K2 2.8 is running in Joomla 3.8.0.

I am now restoring that dev site back to version running Joomla 3.7.5.

I hope this helps.

**Comment by KannanNaidu** [comment]
There is a reported issue with Joomla 3.8 and srcset - https://github.com/joomla/joomla-cms/issues/18077 and there is a fix [#17978](https://github.com/joomla/joomla-cms/pull/17978)

**Comment by williamconifer** [comment]
Thanks Kannan! I really appreciate the help.

**Comment by fevangelou** [comment]
OMFG is all I can say. I'd never thought the J router would mess these paths... Thanks @KannanNaidu for the tip!
