### ISSUE TITLE
K2 items & categories disappear on opencart/joocart hosting accounts

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#421]
Hi guys,

I know this has been raised and solved with Mijoshop, but they have a different approach than the other Opencart integrations. Mijoshop has always been willing to modify the underlying Opencart platform extensively, to the point that they're no longer the same platform.

Anyone that runs Opencart on the same hosting account, or runs an integration that tries to stay in sync with Opencart will have this issue.

It's something I've been dealing with on Joocart lately. The Joocart guys came up with this fix:

`There is a solution for this issue here https://forum.joomla.org/viewtopic.php?t=714723#p2872175 
 
/administrator/components/com_k2/models/categories.php

Replace (line 51): Code: Select all
$query .= " AND c.language = ".$db->Quote($language);

With: Code: Select all
$query .= " AND (c.language = ".$db->Quote($language)." OR c.language = '*')";

Replace (line 147): Code: Select all
$query .= " AND language = ".$db->Quote($language);

With: Code: Select all
$query .= " AND (language = ".$db->Quote($language)." OR language = '*')";

/administrator/components/com_k2/models/items.php

Replace (line 98): Code: Select all
$query .= " AND i.language = ".$db->Quote($language);

With: Code: Select all
$query .= " AND (i.language = ".$db->Quote($language)." OR i.language = '*')";

Replace (line 194): Code: Select all
$query .= " AND language = ".$db->Quote($language);

With: Code: Select all
$query .= " AND (language = ".$db->Quote($language)." OR language = '*')";

This happens because by default, the categories and items have * (asterisk) in the language field, in the database.`

I'm wondering if there's a possibility of a long term fix rather than having to reapply this after each K2 update.

**Comment by fevangelou** [comment]
Sure, that's no problem. To be honest, I was not aware of this issue at all. I'm committing the changes in a while and I'll also check every other query in K2 (e.g. in modules).

**Comment by fevangelou** [comment]
I can confirm that anywhere else the language was queried we already used the right queries.
