### ISSUE TITLE
Refactoring?

### ISSUE THREAD

**Issue by Spudley** [getk2/k2#423]
Hi.

Firstly, I want to thank you for writing and maintaining K2.  :smile: 

Looking through the code-base for K2, I have an itch that I want to scratch: I feel that some of the code could do with being refactored into smaller more manageable pieces. Some of the methods are hundreds of lines of code; it should be relatively easy to cut out chunks and move them into private methods. It might also help with reducing duplicated code.

Would you mind if I submitted a PR for this?

There's obviously a lot of code and I only have limited time, so I'll tackle one bit for the first PR to begin with, and then we can see how it goes from there.

If you have a section of code that you would prefer me to start with? Let me know. Otherwise, I'm happy to pick something for myself.

**Comment by fevangelou** [comment]
I've already started this process as well (if you have a look at the commit log for 2.8.0 and the upcoming 2.8.1), as indeed there are parts that a) could be simplified and b) re-used. For example the JSON output (view) could easily be merged with the standard HTML output in the frontend.

Therefore, I would not mind at all if you wish to submit PRs, so long as the functionality remains the same. I highly recommend you start perhaps with smaller changes, e.g. on a class or function level.

Thank you!

**Comment by fevangelou** [comment]
BTW, formatting-wise let's stick to good ol' PSR-1/2 and not use Joomla's as it adds unnecessary lines of code to format if/else, foreach and other such control structures.

**Comment by Spudley** [comment]
Hi. Awesome. I'll fork and check out tomorrow, and spend a bit of time getting a handle on the code before I really dive into any real changes.

Re "*so long as the functionality remains the same*": absolutely yes; that's the key goal for refactoring.  :smile:

Re formatting: Yes, I also prefer PSR-1/2.

Re "*recommend you start perhaps with smaller changes, e.g. on a class or function level.*": I was thinking about tacking some of the code in `plugins/system/k2.php` for a start. But let me know if you think something else would be better.

I obviously can't guarantee how much time I'll be able to dedicate to it, but I'll make an effort to get something for you this month.

**Comment by fevangelou** [comment]
Sounds great!

**Comment by esedic** [comment]
Are also there any plans to remove Joomla 1.5 code?
Some time ago I did it for fun and kept only Joomla 2.5+ code, I have also removed deprecated stuff like JRequest.

**Comment by Spudley** [comment]
Hello. Not sure if you've had a chance to look at the changes I made for this yet? I was going to carry on, but I wanted some feedback on this lot of changes first.  :)  Thanks.
