### ISSUE TITLE
feature request: Boost the extra fields, pleeeeease :D

### ISSUE THREAD

**Issue by scalpmonkey** [getk2/k2#428]
I started a new website and I was sure that I can pass K2 this time since, you know, Joomla articles grow the last few updates but I was wrong. Templating and customization is a baby child compare to K2, BUT, one thing J! did good all right. Its the customization of the Extra fields.

Please include Render Class, hide/show for the Label and some other juicy stuff in the new update. It relay needs us.

tnx and keep up the good job :D

**Comment by jameswadsworth** [comment]
We added multiple extrafields to K2 for a client, the [PR has been sat their since 2015](https://github.com/getk2/k2/pull/230). We have also added the Joomla Show on for K2 extra fields. If there is real interest from the K2 team to include these features we will update our original PR and create a new PR for the show on.

**Comment by scalpmonkey** [comment]
This is great but for me personally most important is the class for the every separate field and hiding the label. This ways the CSS-ing of the is much more easier. Now I have to override the template and add its alias name as a class in the code.

**Comment by jameswadsworth** [comment]
Are you thinking of something like this?

![render_class](https://user-images.githubusercontent.com/9198869/32913555-fa51fbe6-cb12-11e7-9d1e-7929c65f0aba.png)

**Comment by scalpmonkey** [comment]
Yes. If that gives that specific field class than that is it.
Hiding the label is also pretty important. It can be hidden over css but a button wont hurt 😃

**Comment by jameswadsworth** [comment]
Are you thinking of something like this?

![render_class](https://user-images.githubusercontent.com/9198869/32913555-fa51fbe6-cb12-11e7-9d1e-7929c65f0aba.png)

**Comment by scalpmonkey** [comment]
Repost?

**Comment by kbrookes** [comment]
This looks great @jameswadsworth .

I did a fair amount of testing in v3, and the thing I miss most is being able to extend extraField functionality. This looks really great.

**Comment by jameswadsworth** [comment]
We have show on and render class working on our test server. We'll make a PR request in the next few weeks and then hopefully we can get this included in the next release.

**Comment by kbrookes** [comment]
Any news on this?

**Comment by fevangelou** [comment]
Applying the alias as a class in the loop output of the extra fields is a no-brainer. Noted for 2.9.0.
