### ISSUE TITLE
Removing "Copy of" from titles after using 'Batch' to copy

### ISSUE THREAD

**Issue by apooryousefi** [getk2/k2#429]
After using "Batch" to copy items from one category to another, the copied titles gets a "Copy of" added.
I create for every user a set of item (all with the sames set of titles) by copying the standard items to a new category.

So copying and then opening each item to edit the tile is really time consuming. This addon has no beneficial functionality (since it's a copy to another category). 
So if it is in another category, keep the title and alias as it is.

**Comment by fevangelou** [comment]
Noted.
