### ISSUE TITLE
Call to undefined method K2HelperHTML::loadjQuery()

### ISSUE THREAD

**Issue by valerio-bozzolan** [getk2/k2#430]
Hello.

It seems that K2 `2.6.8` is broken:

    Call to undefined method K2HelperHTML::loadjQuery() in plugins/system/k2/k2.php on line 56

For the records we simply patched commenting [this line](https://github.com/getk2/k2/blob/ead6abddfa6b204cd6ef00bbbacf3182adde8f2e/plugins/system/k2.php#L55):

    // K2HelperHTML::loadjQuery();

I think this bug is fixed yet in newer K2 versions, anyway it may be useful to report this here.

**Comment by valerio-bozzolan** [comment]
I'm self-closing this bug because of it's probably fixed yet.

**Comment by fevangelou** [comment]
Yeap, it's fixed.
