### ISSUE TITLE
K2 Extrafild Multiple Date issue

### ISSUE THREAD

**Issue by destrecords** [getk2/k2#433]
If you select "Multiple" in the additional "Date" field in the flatpickr (v 4.1.4), an error appears:
0 - DateTime::__construct(): Failed to parse time string (2017-12-14, 2017-12-15) at position 12 (2): Double date specification

**Comment by kricore** [comment]
More info here: https://www.joomlaworks.net/forum/k2-en/48630-k2-extrafield-date-issue-multiple-date-format
