### ISSUE TITLE
Article metadata - Add Browser Page Title override

### ISSUE THREAD

**Issue by shoulders** [getk2/k2#435]
currently <title> is set by just using the article name which is fine for most people.

Is it possible to add a Browser Page Title in to the metadata setino of a K2 article. I like to use this field for SEO and find it very useful.

![image](https://user-images.githubusercontent.com/319997/34043727-47279c9e-e19a-11e7-974d-772e63cd51b9.png)

thanks

**Comment by simbus82** [comment]
It's fundamental for SEO and CRO differentiate Meta Title from Article Title. This field could be a must!

**Comment by fevangelou** [comment]
As part of the upcoming K2 Pro Suite of extensions, anything that is related to SEO and more will be separated into another extension which would do EXACTLY what you want and a lot more. Wouldn't it be cool if you could customize for example the metadata that are crawled by FB/Twitter/etc.?

Very, very soon on joomlaworks.net ;)
