### ISSUE TITLE
k2 Tools breadcrumbs does not work with cache

### ISSUE THREAD

**Issue by shoulders** [getk2/k2#443]
When i use k2 Tools to display breadcrumbs for k2 and have the caching enables the module caches one page and will keep on display breadcrumbs for that.

**Example 1:**

https://quantumwarp.com/kb/articles

![image](https://user-images.githubusercontent.com/319997/36539453-cad262ee-17ce-11e8-813d-e4ca679aa290.png)

**Example 2:**

https://quantumwarp.com/kb/articles/content/18-applications

![image](https://user-images.githubusercontent.com/319997/36539470-da87e470-17ce-11e8-8d75-787e2f837f78.png)

Please can you fix the caching of this module.

**Comment by fevangelou** [comment]
Are you using progressive or conservative caching?

The same would occur if you used an active class in the menu system (which is why it's usually recommended to leave the menu modules outside caching in such cases)...

**Comment by shoulders** [comment]
I have done a brief test on my demo site (both types) and could not replicate it. But I will re-check on my live site which is much larger and get some more specific steps to reproduce.

I have updated Joomla a couple of times recently.
