### ISSUE TITLE
X-Content-Powered-By K2 v2.8.0 (by JoomlaWorks)

### ISSUE THREAD

**Issue by shoulders** [getk2/k2#445]
the response header `X-Content-Powered-By K2 v2.8.0 (by JoomlaWorks)` is being set on the homepage of my web and seems to be all other pages.

i would like to disable this because it leave me open to fingerprint attacks.

This is also added `<link href="/components/com_k2/css/k2.css?v=2.8.0" rel="stylesheet" />`

I would like to disable this aswell. It should only be loaded when needed. I have added it here because they are related and are added by **System - K2** plugin because if i disabled it they are no longer added.

website: https://quantumwarp.com/

Can you make the plugin just work on k2 rather than the whole system?

**Comment by kbrookes** [comment]
I second this request.

I've been working with a couple of penetration test companies for some large-scale clients and this is one of the things they've flagged.

**Comment by fevangelou** [comment]
Will be implemented as an option.

**Comment by github-canni** [comment]
X-Content-Powered-By: K2 v2.10.4 (by JoomlaWorks)
ist set in my installation. Where can I find the option to turn that off?

**Comment by shoulders** [comment]
I had a quick look and could not find this option or a code pull on github
