### ISSUE TITLE
Feature request: Items by tag displayed same as by category

### ISSUE THREAD

**Issue by lausianne** [getk2/k2#446]
I have the category display of my items set up, looks fine. Now I also want to set items into the menu by tag, easy enough. But the display of items by tag is totally different from the display by category - I need both to look exactly the same.

The tag page display override should also automatically adjust to any parameter changes for categories.

**Comment by villykou** [comment]
I have also noticed that in tag view the ratings of the items are not displaying

**Comment by villykou** [comment]
I am so much looking forward to a solution

**Comment by villykou** [comment]
Thank you! I have configured those but still, the options for tag view are limited to the very basics.
e.g. no columns, no size for the image, no hits, no rating e.tc. 
Plus, as I am using word limit in category configuration (for symmetry), in tag view I have a result of showing whole items and all its photos one after the other.
In other words, tag system is almost useless as it destroys the layout of the website.
I have tried to edit tag.php but with no success :(

**Comment by lausianne** [comment]
Closed without comment?

**Comment by fevangelou** [comment]
I'm closing all old issues in preparation of K2 v2.10. After that, I will make a new list for K2 v2.11 with the things that actually make sense to integrate.

For the record, this specific request is actually at the top of my to-do list. Basically a re-organization of all itemlist views to share common options.

**Comment by lausianne** [comment]
Thank you! Very much!

**Comment by fevangelou** [comment]
You're welcome :)
