### ISSUE TITLE
Sub Tags

### ISSUE THREAD

**Issue by AyelGoth** [getk2/k2#452]
The idea is that users can add subtags to a parent tag. Similar to Joomla's label management system. This will be useful to better organize the tags.

**Comment by fevangelou** [comment]
The definitions of tags is that its a flat hierarchical system. Categories are meant to be organized in trees. Tags are flat. No reason to complicate things.

If you want to filter a category's items by certain tag you can either create a menu item or better still, create a module or plugin to automatically do the sub-filtering in any view you want.
