### ISSUE TITLE
Multiple Extra Field Groups & Repeating Extra Fields/Field Groups [Enhancement]

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#453]
This is one that keeps coming up in development for me. While testing K2V3 I very much appreciated the ability to select multiple field groups per category. As it is, I regularly have to create multiple versions of the same field for each extrafield group. I'd love to see this added to future versions of K2.

Even more so, I'd really like to see repeating extra fields, and repeating extra field groups.

An example would be creating an FAQ on a page. The extrafield group would contain two fields:

- Textfield: Question
- Textarea: Answer

Add as many repeats of that group as you need.

With a template override for that item, it'd be child's play to format the results using (for example) Bootstrap reveal layout.

I currently do this with an FAQ category, where each Question/Answer is an item Title/Text, but it's a bit unwieldy and creates extra pages that are then indexable (unless set otherwise) in search.

**Comment by kbrookes** [comment]
Ah, I'd missed that. Is the frontend display MVC? It's something I could use extensively if its display is fully overrideable.

**Comment by ronnyvanderborght** [comment]
It is.  It works more or less identical to k2's custom fields.

<?php foreach($this->item->extraFieldsDataSets as $key=>$dataSet): ?>
    <?php echo $dataSet['fields']['myfieldname']; ?>
<?php endforeach ;?>

**Comment by kbrookes** [comment]
Awesome, thank you :)
