### ISSUE TITLE
Granular Robots: No-Index Items | Category | Both [Enhancement]

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#454]
At present if you want to no-index all items in a category, but index the category itself, you have to do it manually.

Examples of this are for pages which behave like landing pages, but are pulled from items, or FAQ pages (each question/answer pulled from items), or any other instance where you'd like the category view to be indexed, but not the items.

This is probably a more sensible way of handling the intent of one of my previous requests: #406

**Comment by kbrookes** [comment]
Just a followup on this - I've been doing some checking, and category views of categories set to no index/no follow are not indexed, but their items are - so items are showing up in search results even if there's no menu item, no category view with links, no other links to those items.

**Comment by fevangelou** [comment]
Realistically speaking, since the category is the entry point for the items, they should not be indexed. But my guess is that you're probably using Google Analytics and the pages get picked up sideways. Unless you have direct item references elsewhere...

Have you used a crawler beyond Google's tools to test things out?

**Comment by fevangelou** [comment]
You know, the reason we had these meta tags separately in the first place was part of K2 being familiar as com_content is some aspects. These are just switches and the correct way for the new K2 would be to have these as switches directly in the layout options in the category and simply allow the item to inherit whatever value is there.

In the meantime, a K2 or content plugin would check an item's category settings and rewrite the related meta tag accordingly. I could list it under https://github.com/getk2 if you want with you as sole contributor as I've done with the plugin for JCE and JCE's developer (Ryan Demmer).
