### ISSUE TITLE
Pagination ordering doesn't respect category ordering

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#456]
It's a bit odd that the item pagination doesn't respect the category ordering. The conform to 'ordering' order, irrespective of the ordering set to the category itself.

**Comment by fevangelou** [comment]
Is this on a stock installation of K2? And I assume you simply changed the order to "ordering" in the category's params and didn't get the expected result, correct?

**Comment by kbrookes** [comment]
Hi Fotis,

Yes - there's some template overrides, but nothing affecting the functionality of pagination.

And yes, I'm not getting the expected result; if the category item ordering paramater is set to alphabetical, the previous and next item should be the next or previous item in alphabetical order. At present I get the previous/next item in Ordering order.

**Comment by fevangelou** [comment]
The query may be borked somehow. I'll look it up.

**Comment by fevangelou** [comment]
You're right, the query is not correct. Noted to fix before releasing v2.9.0.

**Comment by kbrookes** [comment]
Thanks @fevangelou - probably silly to ask, but is there a rough ETA for that release?

**Comment by fevangelou** [comment]
Coming back to this, ordering for which prev/next items to show currently works by "custom" ordering only. In other words, in the backend items list, if you select a category and then choose to sort by drag and drop, then that ordering will be respected. Obviously it's not really practical in cases like alphabetical lists as you mentioned.

Working on this at the moment. I'll let you know again.

**Comment by kbrookes** [comment]
Thanks for letting me know @fevangelou, much appreciated.
