### ISSUE TITLE
No Comments in Joomla Backend

### ISSUE THREAD

**Issue by ViktorHelwer** [getk2/k2#459]
Xampp 
PHP Version 7.2.10
Database: 5.5.5-10.1.36-MariaDB Xampp
Joomla! 3.8.13 Stable 

Good day,
on one of my websites the comments with the K2 version 2.9.0 work wonderfully. On another website I installed 2.9.1 developer version, then I added some comments in the K2 blog, but these are not displayed in the Joomla backend, but are present in the k2_comments database table!

How can I fix this?

**Comment by fevangelou** [comment]
Does this still occur with the latest export from https://github.com/getk2/k2/archive/master.zip ?
