### ISSUE TITLE
JSite::getMenu in mod_k2_user/helper.php - Using $this when not in object context

### ISSUE THREAD

**Issue by marcin-gryszkalis** [getk2/k2#460]
there's
```
$menu = JSite::getMenu();
```
and it causes "Using $this when not in object context" error on Joomla 3.8 on PHP 7.2
Should be replaced by
```
$menu = JFactory::getApplication()->getMenu();
```

Reported by someone else too: https://www.joomlaworks.net/forum/k2-en/48108-k2-v2-8-not-error-with-php7#163427

**Comment by fevangelou** [comment]
It's fixed already in 2.9.1.
