### ISSUE TITLE
Feature Request/Bug - Authors are not notified when a user comments on their post

### ISSUE THREAD

**Issue by 1seanr** [getk2/k2#466]
I am not sure if this is a setting that I have missed but have been searching for the past 15 min and cant seem to find anything about enabling it.

But I have turned on comments having to be approved before they are visible to other users the problem is however that no one (even the author and primary Joomla email address) is sent an email to notify them a comment has been made or is pending approval. All of the authors that are allowed to post items have access to the back-end so they can approve comments on their own items but there is nothing to notify them and tell them to check the back end when they get a new comment.

**Comment by fevangelou** [comment]
There are a few plugins already to do that. Did you check at K2 Extensions Directory? E.g. https://getk2.org/component/k2/search?searchword=notify
