### ISSUE TITLE
Ultra feature request: Change the editing system

### ISSUE THREAD

**Issue by AyelGoth** [getk2/k2#468]
The feature requested is simple to explain, but difficult to realize. Change the complete article editing system to a block article editing system, similar to extensions such as SP PageBuilder, GridBox, Yootheme Builder or EasyBlog. It would be a radical, intuitive change that will surprise everyone.

**Comment by fevangelou** [comment]
Your "ultra" prefix was spot on. Once there are a few grid editors (in JS) to consider, it could make a "Pro" feature in K2.
