### ISSUE TITLE
Feature Request: Exclude individual items from appearing in "Related Items"

### ISSUE THREAD

**Issue by LTIOfficial** [getk2/k2#469]
I have a large site with several sections that are specific to individual teams/departments, and need the ability to prevent 'some' of their K2 Items from appearing across the rest of the site in various "Related Items" displays (both tags and at the bottom of items).  I've searched (both in the site's K2, as well as numerous web searches) for a switch to stop them from being included, but no joy.

To maybe be clearer, I'm asking for a way to remove select individual K2 items from K2's overall Related Items pool.

Edit: It appears that I am not the only one interested in such a feature:
https://www.joomlaworks.net/forum/k2-en/48773-hide-featured-items-from-latest-related-items

**Comment by fevangelou** [comment]
There is a better solution coming as part of the K2 Pro Suite of extensions: select distinct related items to show below the item, instead of related items by tag.
