### ISSUE TITLE
Warning: preg_replace() and Warning: count() in PHP 7.3

### ISSUE THREAD

**Issue by bdthemes** [getk2/k2#471]
Hi, Getting some warning after update my php 7.3

Warning: count(): Parameter must be an array or an object that implements Countable in \components\com_k2\models\item.php on line 763

Warning: preg_replace(): Compilation failed: invalid range in character class at offset 14 in \components\com_k2\views\item\view.html.php on line 212

Warning: preg_replace(): Compilation failed: invalid range in character class at offset 4 in \components\com_k2\views\item\view.html.php on line 213

NOTE: i am using k2 version 2.9.0 and joomla 3.9.2

**Comment by fevangelou** [comment]
Fixed.

Just grab the latest export from the Github repo and install on top of what you have now: https://github.com/getk2/k2/archive/master.zip
