### ISSUE TITLE
Display language code after the name of the category on all selects in the admin area

### ISSUE THREAD

**Issue by jonrz** [getk2/k2#472]
Some words are written the same in more than one language, and it gets very confusing when we are trying to select the proper category for a content.

Examples would be the English word "Posts", that is used across many languages, or words in latin languages, especially between Portuguese and Spanish, such as "Negócio" (Business), "Grupo" (Group), among others. Also, the name of the company or professional, when used as a category, will (almost) never be translated.

In all dropdowns across K2 there is no indication of the language of the category, so we end up with a list with two or more of the same word, and guess which one is the category in the language we need.

A quick solution would be, for multi-lingual sites, to have the language code be displayed after the name of the category on all dropdowns and selects in the admin area, both in the component views and in the modules (ex.: mod_k2_content).

Please see this example, where for a blog we have the "Posts" category in more than one language.
![image](https://user-images.githubusercontent.com/25874295/51846482-fff94380-235c-11e9-8a48-79cc53a11bdf.png)

This is the result we get when trying to select a category.
![image](https://user-images.githubusercontent.com/25874295/51846656-5a929f80-235d-11e9-8f43-dc4a18c2609f.png)

Thank you.

**Comment by ronnyvanderborght** [comment]
I agree, been having the same issue on different sites. For instance for blog-type articles, in English: Blog, in Dutch: Blog

**Comment by fevangelou** [comment]
Makes sense. Noted to add for v2.10.

Keep in mind that a plugin for mapping K2 items (translation associations) is on the way too to further assist in multilingual sites powered by K2. A working example can be seen at the newly launched website for the National Opera of Greece: https://www.nationalopera.gr/en (click on any K2 item or category and switch language from the left column on desktop)

**Comment by fevangelou** [comment]
It was easy, so it's now fixed in: https://github.com/getk2/k2/commit/04370eadca3944511daa4a1d58a1483885e077f1

Just grab the latest export from the Github repo and install on top of what you have now: https://github.com/getk2/k2/archive/master.zip

**Comment by jonrz** [comment]
@fevangelou 
That was really fast. Thank you!
I'll install and test, and let you know how it goes.
Cheers.
