### ISSUE TITLE
Feature Request: Integration with Joomla Privacy and User Action Logging Features

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#473]
This is something of an issue for a new client with a reasonably high-profile corporate site build.

They want to ensure GDPR compliance, and they want to see logs of user actions. Ideally all on the one place.

It would seem to make sense to me for K2 to integrate with the new Privacy and User Action Logging tools to facilitate this.

(also version control, as per #402 - but that's another request).

**Comment by fevangelou** [comment]
For those in urgent need of logging, you can always grab JoomlaTools' LogMan which has a K2 driver.

**Comment by kbrookes** [comment]
Thanks @fevangelou - not an urgent need at present, but now that I **have** logging in the dashboard, I can see how useful it would be to have better visibility on K2 through the same mechanism.

**Comment by fevangelou** [comment]
Closing as it's accepted. To be implemented for v2.11 or v2.12.
