### ISSUE TITLE
Load IntroText (trough SP PageBuilder) in the Category listing view

### ISSUE THREAD

**Issue by acs-ferreira** [getk2/k2#476]
I'm using SP PageBuilder to build some contents into K2.

In the `item` view, a simple line `<?php echo $this->item->introtext; ?>` loads the PageBuilder content, but in the `category` (listing) view, i just can't load any content from PageBuilder and only `<?php echo $this->item->title; ?>` is triggered and `<?php echo $this->item->introtext; ?>` is ignored.

Is this a correct behavior? Or is there another way to load SP PageBuilder contents in the `category` view?

**Comment by fevangelou** [comment]
Make sure plugins are enabled in the category display settings for item listings, assuming SP PageBuilder is attempting to load something via plugins.

**Comment by acs-ferreira** [comment]
Yes, K2 plugins are enabled in both Item and Category view, perhaps it only loads content on the Item view.
So if i understand well, this might be a plugin issue, not K2, right?

Noted your "BTW".

**Comment by fevangelou** [comment]
That is correct. Keep in mind that even on the itemlist view we trigger plugins, so if everything is on (on your configuration) then it's possible the SP PageBuilder plugin is triggered only on the item view. In any case, ask the extension's developers.

**Comment by acs-ferreira** [comment]
Ok thanks.
