### ISSUE TITLE
Error saving categories - Unknown column 'gallery' in 'field list'

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#477]
Currently running 2.9.1 [Dev build] - downloaded approximately Tues March 5 2019, using in conjunction with Simple Image Gallery Pro version 3.6.5

With SigPro enabled, categories can be saved, but generate the following error:

1054 Unknown column 'gallery' in 'field list'

**Comment by fevangelou** [comment]
This error comes up when you just save a category in K2? What's the integration with SIGPro exactly?

**Comment by kbrookes** [comment]
No integration, except that it's installed and being used. There's a template override for the JWSigPro 'responsive' layout, but nothing that should impact the backend.

Take a look at it in action:

https://www.dropbox.com/s/hotsqnivmgyeqb2/k2-category-save.mov?dl=0

**Comment by fevangelou** [comment]
Is this a new installation or an upgrade?

**Comment by fevangelou** [comment]
You can also check the DB schema here: https://github.com/getk2/k2/blob/master/administrator/components/com_k2/install.mysql.sql#L13

There is no such reference as "gallery" nor "field list" which probably points to a conflict with another K2 extension, not SIGPro.

**Comment by kbrookes** [comment]
It's a new install. I'll look further into it and see if there's any more data I can provide.

**Comment by fevangelou** [comment]
This is indeed a bug, double verified by another user, although not in K2 but in SIGPro.

So I'm issuing an update for SIGPro tomorrow.
