### ISSUE TITLE
K2 plugin onAfterRender mb_string memory exhaust

### ISSUE THREAD

**Issue by pinta83** [getk2/k2#478]
File: plugins/system/k2/k2.php
function: onAfterRender

At the beginning of the function you should add
`
if (JFactory::getApplication()->input->get('option') !== 'com_k2')
	return;
`

The problem is that this event triggers in all cases - every time, not just on K2 views.
Since i have a component that has a lot of html, due to mb-replacements in this part of K2 system plugin, my application hangs...

So either do a check if it's rly K2, or replace the head, not the entire response body... This way it just causes problems :)

**Comment by fevangelou** [comment]
If I do that, then K2 modules that don't appear in K2 pages and yet require stuff from the K2 system plugin would simply not work...

There's a reason we utilized a K2 system plugin in the first place.
