### ISSUE TITLE
Suggest using git tags for versions to make repo navigation easier

### ISSUE THREAD

**Issue by robations** [getk2/k2#481]
I don't know if this is possible within your workflow but adding version tags on a release would make it much easier to diagnose issues and see what has been fixed when. That's all. If not possible feel free to close.

**Comment by fevangelou** [comment]
Generally speaking, nothing's broken in K2. New releases is basically improvement on old features or new additions. So I don't see any point in that. If you doubt a certain commit of code, you can always browse to the commit before that and do an export of K2. Much more practical for you (again, if you believe you've spotted a bug). Then again, you can simply mention the bug (if found) and we'll swiftly resolve it.

**Comment by robations** [comment]
This is less about specific bugs, more there are legitimate reasons to compare versions and see what has changed, or easily see what version corresponds with a specific commit. E.g. if I install v2.9.0, exactly what git hash is this from?

I'd guess most projects on github do this, but not my place to push a particular workflow on anyone :)

**Comment by fevangelou** [comment]
I usually mark the release like so: https://jumpshare.com/v/IdlMJMsBANl5bW0KIxwy

Actual commit is here: https://github.com/getk2/k2/commit/0647d1000e3d6ca25da74352255a76bfb630b565

**Comment by robations** [comment]
Thanks Fotis. Useful to know, but bear in mind Github doesn't provide an easy way to search through commits, whereas with tags you get a nice dropdown menu. If it was me, I'd tag the commit when you do the `Mark v...` commit, but will leave to your discretion.
