### ISSUE TITLE
2.10 - Category templates & display settings not applied

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#482]
I was having issues with extraFields image selects in 2.9.0, so upgraded to 2.10.

When setting the template in the category parameters, the template and display settings are not applied.

The only way to set the category layout is via menu item parameters.

**Comment by fevangelou** [comment]
Works just fine on my end - check for inheritance by another category.

**Comment by kbrookes** [comment]
Definitely no inheritance.

https://www.dropbox.com/s/2eq53ybzjj1e25p/Screenshot%202019-06-15%2008.18.59.png?dl=0

This is a site that was in development under 2.9 then upgraded to 2.10, it could be something that only occurs on an upgraded site?

**Comment by fevangelou** [comment]
Doesn't matter if it's an upgrade. Verify that there is no menu item enforcing another sub-template.

**Comment by fevangelou** [comment]
Any update on this Kelsey?

**Comment by kbrookes** [comment]
Apologies Fotis,

After struggling with it a bit more today to give you a reasonable test-case I realised what was going on.

Although I'd turned off sh404SEF, it had cached the URL, and 'fixed' the parameters, and I'd forgotten to install the k2 sh404SEF plugin. 

I've done that now, and all is well.

**Comment by fevangelou** [comment]
Thanks for letting me know :)
