### ISSUE TITLE
Double headings in edit window

### ISSUE THREAD

**Issue by stimpsonjcat** [getk2/k2#484]
In the frontend editing window there are two headings. The second one is pushing the Basic and Publishing tabs to the right. There's no need for an extra heading.
![Schermafbeelding 2019-07-04 om 15 35 27](https://user-images.githubusercontent.com/3033162/60671035-7c470400-9e72-11e9-8ede-435b0f037d33.png)
![Schermafbeelding 2019-07-04 om 15 35 13](https://user-images.githubusercontent.com/3033162/60671037-7cdf9a80-9e72-11e9-8d18-247db586a858.png)

**Comment by fevangelou** [comment]
Good catch. Noted to fix. Thank you.

**Comment by fevangelou** [comment]
Resolved in K2 v2.10.
