### ISSUE TITLE
Simple Image Galleries not displaying

### ISSUE THREAD

**Issue by stimpsonjcat** [getk2/k2#485]
The SIG Pro K2 plugin doesn't render galleries anymore when galleries are added through K2. Galleries added within the text of an article with {gallery}some-id{/gallery} do work fine, but the one uploaded through K2 fail to render. Even the ones that were created in the past.

I don't know wether this is a K2 or a SIG Pro issue, but it's urgent, because our site is broken now.

**Comment by fevangelou** [comment]
Works just fine on my end. Check for any additional K2 plugins that may break functionality. It would also help if you mentioned which K2/Joomla/SIGPro versions you're using.

**Comment by stimpsonjcat** [comment]
Sorry for not mentioning. 
K2 2.10
Sig Pro 3.6.7

Example of a page with a K2 gallery that worked fine before: https://www.ugenda.nl/lifestyle/stadstekening/item/12842-stadstekenaar-rene-brouns

Example of a page with a Sig Pro Gallery: https://www.ugenda.nl/lifestyle/stadstekening/item/13169

**Comment by fevangelou** [comment]
Do you see the gallery in the K2 item form's Image Gallery tab?

**Comment by stimpsonjcat** [comment]
Yes, the gallery is there. Even if I go to the Sig Pro component, the gallery is fine. If I remove the folder on the server, then an error is displayed that Sig Pro can not render the (K2) gallery, so Sig Pro is trying to render something.
I just disabled all K2 plugins and all non core system plugins, but that didn't help.

**Comment by fevangelou** [comment]
Please check my reply in the JW helpdesk and let's continue this over there. If it's a bug indeed in K2 or SIGPro, I'll update this thread.
