### ISSUE TITLE
K2 display messed up in mobile view

### ISSUE THREAD

**Issue by Simon-Davies** [getk2/k2#487]
On the latest dev version of K2 the display is messed up in mobile view.

See screenshot below:

![Screenshot_20190815-204101_Chrome](https://user-images.githubusercontent.com/713455/63121726-0e2b4c00-bf9d-11e9-9e84-723b464d51bc.jpg)

**Comment by fevangelou** [comment]
The stable version will have this addressed partially. In any case, I don't recommend using your mobile phone for general backend content editing with K2.

**Comment by fevangelou** [comment]
A fully responsive release is scheduled for v2.10.2. Read more here: https://getk2.org/blog/2680-k2-v2101-released
