### ISSUE TITLE
In recent versions of PHP the profile settings are not saved sometimes.

### ISSUE THREAD

**Issue by DanCInOz** [getk2/k2#491]
Please (re-)read this thread.
https://www.joomlaworks.net/forum/k2-en/49486-k2-edit-profile-shows-error-in-frontend-after-change-to-php-7-2-7?start=10#173275

Using the latest code (github.com/getk2/k2/archive/master.zip) I see that the problem is mostly fixed, however an issue still exists:
I no longer receive the Error 0, however the changes will only save under some conditions..

It has to do with the password/password verify fields.

If you do not supply a password, or supply the password in both password+verify fields, the k2 profile as well as any other custom user plugins save.
If you only put the password in the password field (a lot of browsers pre-fill this for you) then only some of the data saves.
In this case:
* The basic user data saves.
* The user.profile plugin data saves.
* The k2 plugin data does not save.
* My own custom user plugin (same code as user profile, just extra fields) does not save.

**Comment by fevangelou** [comment]
Let's continue this over at the forum please.

**Comment by fevangelou** [comment]
Closing as the issue was resolved and not related to K2.
