### ISSUE TITLE
Add a trigger when an attachment is deleted

### ISSUE THREAD

**Issue by pinta83** [getk2/k2#492]
I wrote a K2 plugin that generates jpg previews from pdf attachment that are uploaded in the item, but i had to hack the admin item model so the preview gets deleted when you actually delete the attachment.

Could you please add an onAfterK2DeleteAttachment to the deleteAttachment function in the /administrator/components/com_k2/models/item.php - for instance, between theese two lines

```
$row->delete($id);
$application->close();
```

Something like
```
JPluginHelper::importPlugin('k2');
$dispatcher = JDispatcher::getInstance();
$result = $dispatcher->trigger('onAfterK2DeleteAttachment', array($id, $savepath));
```

**Comment by fevangelou** [comment]
Done :)

**Comment by pinta83** [comment]
I just love you guys :)

**Comment by fevangelou** [comment]
Doing our best :)
