### ISSUE TITLE
Error in Joomla 3.9.12 with latest dev K2 build

### ISSUE THREAD

**Issue by szymas** [getk2/k2#494]
On PHP 7.2.23

Warning: count(): Parameter must be an array or an object that implements Countable in /home/xxx/public_html/templates/xxx/html/com_k2/templates/default/item.php on line 191

where line 191 is 

<?php if($this->item->params->get('itemExtraFields') && count($this->item->extra_fields)): ?>

Any ideas other that turning off warnings?

**Comment by fevangelou** [comment]
This is in your template override, not in K2's core template files. You basically need to update your K2 template overrides with an additional check wherever there is a count() check. Compare the source /components/com_k2/templates/default/item.php with your /templates/xxx/html/com_k2/templates/default/item.php file and search for the additional checks wherever a count() is referenced.

**Comment by szymas** [comment]
Thanks will give it a go!

**Comment by szymas** [comment]
That worked, all set !
