### ISSUE TITLE
Maybe to make some small language upgrade for Flatpickr?

### ISSUE THREAD

**Issue by mixmint** [getk2/k2#495]
Flatpickr starts with the default settings, i.e. the 12 hour time system and English. I think it would be nice if the script for the currently set Joomla language variable would download a language file. Here I mean the file **/administrator/components/com_k2/helpers/html.php** where immediately after line 303 should be

$document->addScript('https://cdn.jsdelivr.net/npm/flatpickr@[version]/dist/l10n/[lang_variable].js');

and also in the file

**/media/k2/assets/js/k2.backend.js** just after line 738 should be found

time_24hr: [true / false],
locale: '[lang_variable]'

Due to the fact that Flatpickr is set in k2.backend.js, where entering the data from php files into Flatpickt may be a problem, you could initiate it in /administrator/components/com_k2/helpers/html.php using addCustomTag().

Such a small change will do many instances well because correcting it manually after each K2 update is a very tedious job.

**Comment by fevangelou** [comment]
Fixed in 2.10.1: https://getk2.org/blog/2680-k2-v2101-released
