### ISSUE TITLE
remove title from non-SEF URLs

### ISSUE THREAD

**Issue by shoulders** [getk2/k2#496]
When you do not have SEF enabled the link contains the article title which seems utterly pointless.
````
index.php?option=com_k2&view=item&id=860:courier-and-shipping-research&Itemid=263
````
is it possible to remove this to give a url like
````
index.php?option=com_k2&view=item&id=860&Itemid=263
````
Both versions of the URL point/route correctly to the appropriate article.

I will be using the non-SEF urls in my articles so when they are presented on the frontend they have correctly built links without me having to use absolute links or relative links that would break if I changed my menu structure. (I wrote a module to extract the non-SEF urls from a page for this purpose)

Related issue https://github.com/getk2/k2-links-for-jce/issues/4 - It should be noted no other Joomla component puts the article title in the non-SEF URLs.

I am using
- Joomla v3.9.8
- K2 v2.9.0

Thanks as always

**Comment by fevangelou** [comment]
Last time I checked, com_content did that:

`/index.php?option=com_content&view=article&id=1:getting-started&catid=2&Itemid=117&lang=en`

What you ask requires changing quite a few parts in K2's code for what is really a personal preference.

**Comment by shoulders** [comment]
This is a copy of a link  from my site using a Joomla article
````
index.php?option=com_content&view=article&id=23&Itemid=873
````

**Comment by fevangelou** [comment]
It may come from a module that does not properly output all URL params...

**Comment by shoulders** [comment]
I will have a look where this is getting added in K2 if I get chance because I would love this to get removed. I am guessing it is in the router.

I know you guys are currently busy with the new version.
