### ISSUE TITLE
Error: Call to undefined method JEventDispatcher::getContent()

### ISSUE THREAD

**Issue by jameswadsworth** [getk2/k2#497]
Since Joomla 3.8.11 and above when overriding the Joomla registration form with the K2 plugin on all sites using K2 we get the following error:

Error: Call to undefined method JEventDispatcher::getContent(): Call to undefined method JEventDispatcher::getContent()

Searching the internet there are many other users who experiencing the same issue: https://www.joomshaper.com/forums/blank-page-and-fatal-error-jeventdispatcher-getcontent

We have found some temporary solutions:
1) disable the readmore editor plugin
2) remove the code that was added in the commit: https://github.com/joomla/joomla-cms/pull/17907/commits
3) disable the K2 system plugin but that breaks the site. 

We have found that removing the following code in the K2 system plugin in lines 501-503
```
$wysiwyg = JFactory::getEditor();
$editor = $wysiwyg->display('description', $K2User->description, '100%', '250px', '', '', false);
$view->assignRef('editor', $editor);
```

and removing the description field from the register.php file in templates gets the site back up and running. 

Reading the message boards of Joomla this bug is problem with 3rd party extensions not Joomla itself:
https://forum.joomla.org/viewtopic.php?t=965218
https://forum.joomla.org/viewtopic.php?t=964237
https://forum.joomla.org/viewtopic.php?t=964486

Can this bug be fixed on the K2 side?

**Comment by fevangelou** [comment]
The quick way to fix this now is to just disable the K2 Profile option under the Advanced tab in the K2 Settings: https://jmp.sh/qaZeOKG

I will have a look and fix it for 2.10.1 (out tomorrow - if I make it) or for 2.10.2 (in 2-3 weeks after that).

**Comment by fevangelou** [comment]
By the way, I just checked on a vanilla Joomla/K2 installation with TinyMCE or JCE, plus the plugins in Joomla for the extended user profile and terms. The register form is properly extended without issues by K2 and the user is registered.

Did you have any other plugins enabled? E.g. Joomla's reCaptcha, 3rd party user or system plugins?

**Comment by fevangelou** [comment]
Closing as there is no response from the OP.
