### ISSUE TITLE
Category browser title override does not work in 2.10.0

### ISSUE THREAD

**Issue by afonic** [getk2/k2#498]
I believe that overriding the browser title though the menu's parameters does no longer work.

At components/com_k2/views/itemlist/view.html.php at line 751:

`if (is_object($menuActive) && isset($menuActive->params)) {`

will always be false, since $menuActive->params is protected.

I think you have already refactored this part but this bug should be fixed asap imho because it can seriously affect SEO in many websites.

Thanks,

Iosif

**Comment by fevangelou** [comment]
This has been fixed already in v2.10.1. You can try out the GitHub copy.

**Comment by afonic** [comment]
That's good to know, I would rush that because everybody is updating to 2.10.0 right now through Joomla and that's serious. In many cases the category name might be totally irrelevant from what you need the page title to be, SEO-wise.

**Comment by fevangelou** [comment]
2.10.1 will be out today or Monday tops.

**Comment by afonic** [comment]
Great! Thanks for this update, it works great so far!
