### ISSUE TITLE
Annoying notification 

### ISSUE THREAD

**Issue by fredtep** [getk2/k2#499]
Hi,
I've just downloaded K2 v2.10.0. My first impression is good. Thanks for your work.
As a web designer, I find it quite annoying to have to close the notification bar to access the button (modify, publish...) I believe it would be better if this notification bar was between the buttons and the filters
I'm coding as well and I'm willing to contribute but I don't really know where to look for the file to modify. If someone can tell me which file to look at and if you find my request to your taste, I'll be glad to help...
![K2-before](https://user-images.githubusercontent.com/28731248/69651338-37657900-1070-11ea-9e05-70d18619be29.jpg)
![K2-after](https://user-images.githubusercontent.com/28731248/69651354-3df3f080-1070-11ea-9cdd-041953f48639.jpg)

**Comment by fevangelou** [comment]
Fixed in 2.10.1: https://getk2.org/blog/2680-k2-v2101-released
