### ISSUE TITLE
I noticed another problem with the calendar

### ISSUE THREAD

**Issue by mixmint** [getk2/k2#500]
While input #created and #publish_up must contain the correct date and time, #publish_down does not have to. The problem is that the value once delivered to the input field does not want to be deleted in any way ... okay: almost. This can only be done by editing the input value in the loaded html in the Browser Developer Tool.
This may be related to manually correcting the input value in all three fields. The manually entered value is accepted only after tapping the enter key.

**Comment by fevangelou** [comment]
See this thread please: https://www.joomlaworks.net/forum/k2-en/51378-annoying-error-with-publishing-dates

K2 v2.10.2 (dev) from this repo is already switched to v4.5.7 of Flatpickr.
