### ISSUE TITLE
Cannot clear date field on item 

### ISSUE THREAD

**Issue by kernusr** [getk2/k2#501]
When you create or edit material k2 and accidentally click on an empty field for a date - it is automatically filled. Clear field fails

![ice_video_20191206-183825](https://user-images.githubusercontent.com/16020878/70335130-c2f0be00-1857-11ea-9427-9051105d7c2b.gif)

**Comment by fevangelou** [comment]
Discussed here already https://www.joomlaworks.net/forum/k2-en/51378-annoying-error-with-publishing-dates and resolved in v2.10.2 (dev).

You can either wait for the official release (around next week) or you can download the dev version from: https://github.com/getk2/k2/archive/master.zip
