### ISSUE TITLE
K2 attachment field title attribute optional text

### ISSUE THREAD

**Issue by obcinajesenice** [getk2/k2#503]
In K2 attachement tab, field 'Title attribute' ignore optional text, if you put it in, it just ignores it and writes default filename instead.

**Comment by fevangelou** [comment]
The "default filename" you mention is what gets displayed in the frontend of your site or in the K2 attachments control in the item edit form?

**Comment by obcinajesenice** [comment]
Both, in front end and admin edit mode. Just instaled latest devk2, it still does it.

**Comment by obcinajesenice** [comment]
uhhh, i just closed comment, didn't wan to :O

**Comment by fevangelou** [comment]
I'll test again and get back to you.

**Comment by obcinajesenice** [comment]
Hej, now it works with K2 v2.10.3 [Dev Build 20191219], thank you!
