### ISSUE TITLE
Default User Groups only installed on update not during install

### ISSUE THREAD

**Issue by jameswadsworth** [getk2/k2#516]
Not sure if this is the intended behaviour, but I would expect the default user groups to be installed upon installation not just when running an update.

**Comment by fevangelou** [comment]
I assume you mean the opposite. Upon initial setup (and given that there is no existing data) we setup the default K2 user groups.

**Comment by jameswadsworth** [comment]
No I mean that when you clean install K2 the user groups are not installed. See screenshot of clean install K2 2.10.3 on Joomla 3.9.18. 
![Selection_045](https://user-images.githubusercontent.com/9198869/82250747-f4f86700-9943-11ea-8005-76adc64eb8ac.png)

If you run the installation of K2 again so it runs as an update then at this point you get the user groups. 

![Selection_046](https://user-images.githubusercontent.com/9198869/82251246-c0d17600-9944-11ea-8933-68e96621f4ef.png)

**Comment by fevangelou** [comment]
You're absolutely right. This is a leftover that should be moved to installations as well (besides updates).

Noted to fix for v2.10.4.

As always, thanks for the extra eyes James :)

**Comment by jameswadsworth** [comment]
An extra pair of eyes always helps! We'll test in the 2.10.4 then close if all good.

**Comment by fevangelou** [comment]
Resolved. The first 2 default groups are now properly set in the relevant installer script (so we keep the install SQL statements clean).

To clarify, this issue only affected J1.6 or newer. J1.5 was properly setting these default groups (for anyone still using J1.5)...

Thanks again for your input.
