### ISSUE TITLE
More extra fields weirdness

### ISSUE THREAD

**Issue by kbrookes** [getk2/k2#518]
In v2.10.1 when I create an extra field there's two specific areas of oddness:

1) If I already have a category created, the new field will default to that category, but won't save because "you must select a category or create a new one". Clicking and selecting the existing category doesn't resolve the issue.

Selecting 'create category', then clicking again and selecting the existing category fixes the issue and allows it to be saved.

2) 'Undefined' fills every field. It's a pain, because a lot of my existing templates rely on "!empty" for extra field data.

**Comment by kbrookes** [comment]
This seems to be an issue with the single site I was on. Started a completely fresh site and the issue didn't re-occur.

**Comment by fevangelou** [comment]
Fixed in 2.10.3. You can test it out.

**Comment by kbrookes** [comment]
Yes, definitely fixed in 2.10.3
