### ISSUE TITLE
PHP notices when viewing trashed categories

### ISSUE THREAD

**Issue by jameswadsworth** [getk2/k2#519]
How to recreate: 
Go to settings and set showItemsCounterAdmin to 0. Then go view the categories, select the filter "Trashed".

Result:
Notice: Undefined property: stdClass::$numOfItems in /shared/httpd/joomla39xx/public_html/administrator/components/com_k2/views/categories/tmpl/default.php on line 158
Notice: Undefined property: stdClass::$numOfTrashedItems in /shared/httpd/joomla39xx/public_html/administrator/components/com_k2/views/categories/tmpl/default.php on line 158

**Comment by jameswadsworth** [comment]
Closing as this issue is no longer present after updating to 2.10.3

**Comment by fevangelou** [comment]
Thank you James :)
