### ISSUE TITLE
feature of sort attachments.

### ISSUE THREAD

**Issue by prma85** [getk2/k2#52]
I would suggest a new feature that can help many people.
Would functionality Sort attachments.

I created a new parameter in the global settings Chamdo "Ordering attachment" with the options "By name - Ascending, By Name - Descending, Newest first, oldest first ones, by id"

I changed the code of the following files:
components/com_k2/models/item.php - line 1591
administrator/components/com_k2/models/item.php - line 1106

the old code:
$query = "SELECT \* FROM #__k2_attachments WHERE itemID=".$itemID;

the new code:
$query = "SELECT \* FROM #__k2_attachments WHERE itemID=".$itemID." ORDER by ".$params->get("orderAttachments");

**Comment by leeburstroghm** [comment]
Would add an order number field, to be able to ORDER BY, order_num . Really, this is not part of the core k2.. its little things like this, just lack of consideration for basic function that keeps K2 from becoming bigger than it is..

**Comment by corconsulting** [comment]
a sort option for attachments would be a great idea.
