### ISSUE TITLE
Black dots in backend 2.10.3

### ISSUE THREAD

**Issue by jameswadsworth** [getk2/k2#521]
After upgrading to K2 2.10.3 all over the backend where there is the li html tag black dots are rendered. While nothing is broken it would look better without them.

![Selection_042](https://user-images.githubusercontent.com/9198869/81832464-714f0c80-9536-11ea-895f-94fc20c2fc96.png)

**Comment by fevangelou** [comment]
It's fixed in v2.10.4 which should be out by Friday or Monday (18th of May) tops.

**Comment by jameswadsworth** [comment]
Great we look forward to testing.
