### ISSUE TITLE
The "$itemlistModel" is not used anywhere in the router.php file

### ISSUE THREAD

**Issue by Yiannistaos** [getk2/k2#526]
In the file: \components\com_k2\router.php
Lines 28-29
require_once(JPATH_SITE.'/components/com_k2/models/itemlist.php'); 
$itemlistModel = newK2ModelItemlist;

I think that these lines are not required here.
Does the variable "$itemlistModel" used anywhere in the router.php file?

**Comment by fevangelou** [comment]
Removed already - thank you.
