### ISSUE TITLE
Attachment link in item not work with SEF URL active

### ISSUE THREAD

**Issue by nucleocreativo** [getk2/k2#528]
Hello,

the attachment item link return 404 error with the SEF URL option is active.

Thanks

**Comment by fevangelou** [comment]
Please use the K2 forum https://www.joomlaworks.net/forum/k2 for such questions.

**Comment by nucleocreativo** [comment]
Sorry but I think that it is code problem before the row href=<?php echo $attachment->link; ?> return error 404, with the row href=<?php echo JRoute::_('media/k2/attachments/'.$attachment->filename); ?> work! Thanks

**Comment by fevangelou** [comment]
Which file and line exactly?

**Comment by nucleocreativo** [comment]
The files are item.php and category-item.php in default template

**Comment by fevangelou** [comment]
Yes, but where exactly? Inside your template's html/com_k2/ folder?

**Comment by nucleocreativo** [comment]
In this directory: components/com_k2/templates/default

**Comment by fevangelou** [comment]
Looks like you have Advanced SEF enabled. This is the issue in K2 v2.10.3. It'll be resolved in the upcoming K2 v2.10.4.

In the meantime you can just use the URL router from 2.10.2. More here: https://github.com/getk2/k2/issues/522

**Comment by nucleocreativo** [comment]
Thanks!
