### ISSUE TITLE
Array to string conversion warning in K2 Content module

### ISSUE THREAD

**Issue by jameswadsworth** [getk2/k2#529]
See attached screenshot of K2 Content module version 2.10.3 on Joomla 3.9.18 on php 7.3

![Selection_059](https://user-images.githubusercontent.com/9198869/84005121-87e55980-a964-11ea-942d-8b132230507f.png)

**Comment by jameswadsworth** [comment]
Line 64 in moduletemplate.php should be:

return JHTML::_('select.genericlist', $options, $fieldName, 'class="inputbox"', 'value', 'text', $value, $name);

**Comment by fevangelou** [comment]
Fixed already in v2.10.4 (dev):

https://github.com/getk2/k2/commit/e171c562ec9195937a0d15722472619f833fc024#diff-d658b70023785a9fe239e1c07ae81f32

The last parameter isn't really needed in this case, so it's just omitted.

**Comment by jameswadsworth** [comment]
Great.
