### ISSUE TITLE
Tabs and Sortables error

### ISSUE THREAD

**Issue by RoseGomez** [getk2/k2#531]
Hello, I see administrator/components/com_k2/helpers/html.php brings up a jquery file that is no longer available and makes tabs not work when editing an item. I replaced the source to https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.24/jquery-ui.min.js on line 308, this should probably be corrected in new versions. 
Thanks!

**Comment by fevangelou** [comment]
The file is just fine as I mentioned in the forum and comes from jQuery's CDN. If you can't load the file, you probably have a network issue with that CDN.
