### ISSUE TITLE
Problem with posting the article on facebook 

### ISSUE THREAD

**Issue by ARTIS-MEDIA** [getk2/k2#537]
Hi, I found a minor problem in K2 v2.10.4 Bulid 20210329. When you publish a new article on facebook, facebook downloads the picture from the previous article. Back to K2 v2.10.4
Build 20210227 fixes the problem.

**Comment by fevangelou** [comment]
The URLs for sharing come through meta tags which are unchanged. It's most likely some templating issue on your side (e.g. custom injected meta though item.php)...

**Comment by fevangelou** [comment]
Switch to the latest release and send me a URL to verify if you like...

**Comment by ARTIS-MEDIA** [comment]
The problem appeared only with the latest version. I pass the page. https://www.miastojaslo.pl

**Comment by fevangelou** [comment]
I check some item: https://www.miastojaslo.pl/aktualnosci/3498-koronawirus-w-polsce-przedluzone-obostrzenia-z-pewnym-wyjatkiem.html

Indeed the FB image was wrong, it did not look like the image visible on the item's content.

Then I checked the meta tags and code and found that some non-K2 image is being placed as the FB sharing image: https://www.miastojaslo.pl/images/aktualnosci_2020/spis-ludnosci/samospis_kwiecien.jpg

So there must be some plugin that attaches the wrong image there. Moreover, there is no defined K2 image (from the "Image" tab) and as such K2 cannot create the relevant meta tag for images for sharing on FB/Twitter.

So it's clearly not a K2 bug.

**Comment by ARTIS-MEDIA** [comment]
Then why the previous version [Dev Build 20210227] works fine? I skipped bulid 227 and check it out now.

**Comment by fevangelou** [comment]
You are not using K2 images. Whatever you see is the behaviour of some other plugin.

**Comment by ARTIS-MEDIA** [comment]
Yes, I am using Phoca Open Graph Content Plugin 3.1.12 but without it facebook does not download pictures. It does not change the fact that some changes were made to the latest bulid and it stopped working properly. I have turned off the plugin now and you can see.

**Comment by ARTIS-MEDIA** [comment]
K2 images are of very poor quality. The thumbnails you create are much larger than the original photo. Why are so many additional copies of photos generated? What can not be set so as not to generate additional photos unnecessarily? Can K2 use the original photo instead of creating a bad quality thumbnail?

**Comment by ARTIS-MEDIA** [comment]
Using phoca plugin is incorrectly downloaded <meta property = "og: image" than <meta property = "og: url" The problem appeared in the new K2 bulid
