### ISSUE TITLE
Problem occurred while try to create new category with the PHP & MySQL 8  

### ISSUE THREAD

**Issue by ittoufiq** [getk2/k2#538]
Fatal error: Array and string offset access syntax with curly braces is no longer supported media/k2/assets/vendors/verot/class.upload.php/src/class.upload.php on line 2726

Here is the solution 

File location 

`media/k2/assets/vendors/verot/class.upload.php/src/class.upload.php`

Find out this code 
`$last = strtolower($size{strlen($size)-1});`

And replace with this code 

`$last = strtolower($size[strlen($size)-1]);`

**Comment by fevangelou** [comment]
Thanks, it's been fixed already in the repo (for some time now)...

**Comment by ittoufiq** [comment]
> Thanks, it's been fixed already in the repo (for some time now)...

Thanks
