### ISSUE TITLE
K2 upgrade to joomla 4?

### ISSUE THREAD

**Issue by ARTIS-MEDIA** [getk2/k2#541]
Hello, when can the K2 upgrade to joomla 4 be expected?

**Comment by ARTIS-MEDIA** [comment]
Hello, I renew my question. What about upgrading to joomla 4? When will K2 be compatible with php 8?

**Comment by raramuridesign** [comment]
@fevangelou Is this being looked at?

**Comment by mahjnalisha** [comment]
Any information on new release supporting joomla 4?

**Comment by ARTIS-MEDIA** [comment]
As usual, a delay of at least one year. It's a pity because K2 is great.

**Comment by fevangelou** [comment]
https://www.joomlaworks.net/forum/k2-en/63655-k2-and-joomla-4?start=40#179733
