### ISSUE TITLE
Media manager doesn't work on php 8

### ISSUE THREAD

**Issue by ARTIS-MEDIA** [getk2/k2#548]
Hello, the php 8 media manager doesn't work.
I receive such a message.

Invalid backend response.
Error occurred on the server side.
HTTP error 500

**Comment by jameswadsworth** [comment]
Hi I can confirm the same issue on  server running php 8.0.15

> Invalid backend response.
Data is not JSON.
<br /> <b>Fatal error</b>: Array and string offset access syntax with curly braces is no longer supported in <b>/shared/httpd/joomla39xx/public_html/media/k2/assets/vendors/studio-42/elfinder/php/elFinder.class.php</b> on line <b>2614</b><br />

**Comment by fevangelou** [comment]
Resolved in K2 v2.11 (dev): https://getk2.org/downloads/?f=K2_Development_Release.zip
