### ISSUE TITLE
Behaviour of Comments Module in Top Commneters mode

### ISSUE THREAD

**Issue by jameswadsworth** [getk2/k2#550]
When we have comments "enabled for everyone". When we configure the comments module in Top Commenters mode the module doesn't show any of the non-registered commenters. It this the expected behaviour and why?

**Comment by fevangelou** [comment]
Yes, because registrered commenters can be filtered and we can count their comments. You can't (and shouldn't) do that for anonymous comments which might be full of spam or profanity.
