### ISSUE TITLE
K2_v2.11.20230111-Jrequest Error on install Joomla 4

### ISSUE THREAD

**Issue by MrPJ1751** [getk2/k2#558]
I read that you are looking for testing on the Joomla4 build.
This is a fresh install with a few components that have successfully made the transition to J4!

I installed K2_v2.11.20230111 which seemed liked the newest version and have an error on all aspects of the component.
An error has occurred.
0 Class "JRequest" not found

looking forward to the updated component working. 
Thanks 
PJ

**Comment by fevangelou** [comment]
It's not ready yet for J4. The plan is to release the update by June 2023.

**Comment by MrPJ1751** [comment]
Thank you for the update, I realized I read an article incorrectly. :(. But
this is the information I needed

**Comment by raramuridesign** [comment]
@fevangelou Any idea when K2 for J4/J5 will be released?
M.

**Comment by MrPJ1751** [comment]
I have given up all hope... last rumor I heard is they are attempting to
rewrite for WordPress and Joomla.
I have moved on but also other good extensions will fall by the wayside due
to the idiots at Joomla who completely changed things to make everyone
rewrite their code for joomla4...

**Comment by fevangelou** [comment]
WP is something to consider for the future. K2 will be available for J4/J5 once we get the time to finish work for it (client projects in development hold us back).

That being said, it's true the current Joomla team are amateurs (both as programmers as well as people in business), living in their own bubble. They've lost and shred of trust NOT to fuckup BC in the future.

Consider the mess they've created and for what actual benefit to the end user? Workflows? WP backend lookalike? This is where we laugh hard...

**Comment by PhilippSPOTTERON** [comment]
Hi @fevangelou , any news on J4/J5 update or the process?
thanks!

**Comment by HDInfautre** [comment]
Hi
Same question
I wanted to register on the forum but it didn't work ?
I wonder if the project is not stopped for J4/J5 ??

**Comment by fgsw** [comment]
joomlaworks.net: [K2 will not be made available for Joomla 4/5 - change of course](https://www.joomlaworks.net/blog/item/314-k2-will-not-be-made-available-for-joomla-4-5-change-of-course)
