### ISSUE TITLE
[SECURITY] Arbitrary File Upload vulnerability

### ISSUE THREAD

**Issue by GatekeeperBuster** [getk2/k2#561]
Recently, our team found a Arbitrary File Upload vulnerability,The vulnerability logic is present in the file:
https://github.com/getk2/k2/blob/master/media/k2/assets/vendors/verot/class.upload.php/src/class.upload.php#L3104
![image](https://github.com/user-attachments/assets/89a1e6e2-4378-4d12-bf2c-998f2576de4c)
The suffix blacklist detection utilizes a regular expression with $/i. Attackers can bypass this blacklist detection by using `1.php[space]`, `1.php.` or Windows-specific characters like `1.php::$DATA`.We have submitted the issue to the component developer:https://github.com/verot/class.upload.php/issues/187

**Comment by williamconifer** [comment]
Now that Verot has fixed this issue, when will this fix be available for K2?

**Comment by raramuridesign** [comment]
@fevangelou Would you mind looking into this ?

**Comment by fevangelou** [comment]
Thank you @GatekeeperBuster for letting us know :) Appreciate it.

The fix has been implemented and the new build is already live folks.
