### ISSUE TITLE
Feature request: option to disable generic and other views

### ISSUE THREAD

**Issue by betweenbrain** [getk2/k2#60]
In one of our implementations of K2, we have had some issues with the generic and other views being indexed by search engines. Now that they have been indexed, and we are aware of the issue, we have configured K2 to not show information on those pages, but they are still accessible (blank) pages. 

It would be very beneficial to be able to disable all views, even ones like author and tag pages, so that users can have very granular control of what is shown and where.

**Comment by raramuridesign** [comment]
Hi Fotis
would you consider adding this to the core ?
